create table authors
(
    id   serial
        primary key,
    name varchar(255)
        constraint uk_9mhkwvnfaarcalo4noabrin5j
            unique
);

alter table authors
    owner to postgres;

INSERT INTO public.authors (id, name) VALUES (1, 'J.K. Rowling');
INSERT INTO public.authors (id, name) VALUES (2, 'Mary GrandPr?©');
INSERT INTO public.authors (id, name) VALUES (3, 'W. Frederick Zimmerman');
INSERT INTO public.authors (id, name) VALUES (4, 'Douglas Adams');
INSERT INTO public.authors (id, name) VALUES (5, 'Stephen Fry');
INSERT INTO public.authors (id, name) VALUES (6, 'Bill Bryson');
INSERT INTO public.authors (id, name) VALUES (7, 'J.R.R. Tolkien');
INSERT INTO public.authors (id, name) VALUES (8, 'Chris   Smith');
INSERT INTO public.authors (id, name) VALUES (9, 'Christopher  Lee');
INSERT INTO public.authors (id, name) VALUES (10, 'Richard Taylor');
INSERT INTO public.authors (id, name) VALUES (11, 'Jude Fisher');
INSERT INTO public.authors (id, name) VALUES (12, 'Dave Thomas');
INSERT INTO public.authors (id, name) VALUES (13, 'David Heinemeier Hansson');
INSERT INTO public.authors (id, name) VALUES (14, 'Leon Breedt');
INSERT INTO public.authors (id, name) VALUES (15, 'Mike Clark');
INSERT INTO public.authors (id, name) VALUES (16, 'Thomas  Fuchs');
INSERT INTO public.authors (id, name) VALUES (17, 'Andreas  Schwarz');
INSERT INTO public.authors (id, name) VALUES (18, 'Gary Paulsen');
INSERT INTO public.authors (id, name) VALUES (19, 'Donna Ickes');
INSERT INTO public.authors (id, name) VALUES (20, 'Edward Sciranko');
INSERT INTO public.authors (id, name) VALUES (21, 'Keith Vasconcelles');
INSERT INTO public.authors (id, name) VALUES (22, 'Molly Hatchet');
INSERT INTO public.authors (id, name) VALUES (23, 'Dale Peck');
INSERT INTO public.authors (id, name) VALUES (24, 'Angela Knight');
INSERT INTO public.authors (id, name) VALUES (25, 'Sahara Kelly');
INSERT INTO public.authors (id, name) VALUES (26, 'Judy Mays');
INSERT INTO public.authors (id, name) VALUES (27, 'Marteeka Karland');
INSERT INTO public.authors (id, name) VALUES (28, 'Kate Douglas');
INSERT INTO public.authors (id, name) VALUES (29, 'Shelby Morgen');
INSERT INTO public.authors (id, name) VALUES (30, 'Lacey Savage');
INSERT INTO public.authors (id, name) VALUES (31, 'Kate Hill');
INSERT INTO public.authors (id, name) VALUES (32, 'Willa Okati');
INSERT INTO public.authors (id, name) VALUES (33, 'Delia Sherman');
INSERT INTO public.authors (id, name) VALUES (34, 'Patricia A. McKillip');
INSERT INTO public.authors (id, name) VALUES (35, 'Zilpha Keatley Snyder');
INSERT INTO public.authors (id, name) VALUES (36, 'Kate Horsley');
INSERT INTO public.authors (id, name) VALUES (37, 'Philippa Carr');
INSERT INTO public.authors (id, name) VALUES (38, 'Edward P. Jones');
INSERT INTO public.authors (id, name) VALUES (39, 'Kevin R. Free');
INSERT INTO public.authors (id, name) VALUES (40, 'Satyajit Das');
INSERT INTO public.authors (id, name) VALUES (41, 'Mark Smylie');
INSERT INTO public.authors (id, name) VALUES (42, 'John McPhee');
INSERT INTO public.authors (id, name) VALUES (43, 'William Howarth');
INSERT INTO public.authors (id, name) VALUES (44, 'Wendy Wasserstein');
INSERT INTO public.authors (id, name) VALUES (45, 'Heidi Hayes Jacobs');
INSERT INTO public.authors (id, name) VALUES (46, 'Heidi Boyd');
INSERT INTO public.authors (id, name) VALUES (47, 'Heidi Baker');
INSERT INTO public.authors (id, name) VALUES (48, 'Rolland Baker');
INSERT INTO public.authors (id, name) VALUES (49, 'Johanna Spyri');
INSERT INTO public.authors (id, name) VALUES (50, 'Beverly Cleary');
INSERT INTO public.authors (id, name) VALUES (51, 'Angelo  Rinaldi');
INSERT INTO public.authors (id, name) VALUES (52, 'Heidi Murkoff');
INSERT INTO public.authors (id, name) VALUES (53, 'Sharon Mazel');
INSERT INTO public.authors (id, name) VALUES (54, 'Arlene Eisenberg');
INSERT INTO public.authors (id, name) VALUES (55, 'Sandee Hathaway');
INSERT INTO public.authors (id, name) VALUES (56, 'Mark D. Widome');
INSERT INTO public.authors (id, name) VALUES (57, 'Heidi Fleiss');
INSERT INTO public.authors (id, name) VALUES (58, 'Libby Keatinge');
INSERT INTO public.authors (id, name) VALUES (59, 'Frank Herbert');
INSERT INTO public.authors (id, name) VALUES (60, 'Brian Herbert');
INSERT INTO public.authors (id, name) VALUES (61, 'Kevin J. Anderson');
INSERT INTO public.authors (id, name) VALUES (62, 'Gary Russell');
INSERT INTO public.authors (id, name) VALUES (63, 'Bryce Courtenay');
INSERT INTO public.authors (id, name) VALUES (64, 'John C. Maxwell');
INSERT INTO public.authors (id, name) VALUES (65, 'Stephen R. Graves');
INSERT INTO public.authors (id, name) VALUES (66, 'Thomas G. Addington');
INSERT INTO public.authors (id, name) VALUES (67, 'Dave Lakhani');
INSERT INTO public.authors (id, name) VALUES (68, 'Louis E. Catron');
INSERT INTO public.authors (id, name) VALUES (69, 'Adam Ginsberg');
INSERT INTO public.authors (id, name) VALUES (70, 'Marsha Collier');
INSERT INTO public.authors (id, name) VALUES (71, 'Chris Malta');
INSERT INTO public.authors (id, name) VALUES (72, 'Lisa Suttora');
INSERT INTO public.authors (id, name) VALUES (73, 'Julia Wilkinson');
INSERT INTO public.authors (id, name) VALUES (74, 'Lucas Carlson');
INSERT INTO public.authors (id, name) VALUES (75, 'Leonard Richardson');
INSERT INTO public.authors (id, name) VALUES (76, 'Ruby Ann Boxcar');
INSERT INTO public.authors (id, name) VALUES (77, 'Rob Orsini');
INSERT INTO public.authors (id, name) VALUES (78, 'Leo Tolstoy');
INSERT INTO public.authors (id, name) VALUES (79, 'Richard Pevear');
INSERT INTO public.authors (id, name) VALUES (80, 'Larissa Volokhonsky');
INSERT INTO public.authors (id, name) VALUES (81, 'David Magarshack');
INSERT INTO public.authors (id, name) VALUES (82, 'Priscilla Meyer');
INSERT INTO public.authors (id, name) VALUES (83, 'John Bayley');
INSERT INTO public.authors (id, name) VALUES (84, 'Marianne Sturman');
INSERT INTO public.authors (id, name) VALUES (85, 'Amy Mandelker');
INSERT INTO public.authors (id, name) VALUES (86, 'Constance Garnett');
INSERT INTO public.authors (id, name) VALUES (87, 'Louise Maude');
INSERT INTO public.authors (id, name) VALUES (88, 'Aylmer Maude');
INSERT INTO public.authors (id, name) VALUES (89, 'Gloria Goldreich');
INSERT INTO public.authors (id, name) VALUES (90, 'Anthony Thorlby');
INSERT INTO public.authors (id, name) VALUES (91, 'Mulk Raj Anand');
INSERT INTO public.authors (id, name) VALUES (92, 'E.M. Forster');
INSERT INTO public.authors (id, name) VALUES (93, 'John Banville');
INSERT INTO public.authors (id, name) VALUES (94, 'Eliot Ness');
INSERT INTO public.authors (id, name) VALUES (95, 'Oscar Fraley');
INSERT INTO public.authors (id, name) VALUES (96, 'Narendra Jadhav');
INSERT INTO public.authors (id, name) VALUES (97, 'V.T. Rajshekar');
INSERT INTO public.authors (id, name) VALUES (98, 'Y.N. Kly');
INSERT INTO public.authors (id, name) VALUES (99, 'Vasant Moon');
INSERT INTO public.authors (id, name) VALUES (100, 'Gail Omvedt');
INSERT INTO public.authors (id, name) VALUES (101, 'Eleanor Zelliot');
INSERT INTO public.authors (id, name) VALUES (102, 'Barry R. Cournoyer');
INSERT INTO public.authors (id, name) VALUES (103, 'John Carratello');
INSERT INTO public.authors (id, name) VALUES (104, 'Patty Carratello');
INSERT INTO public.authors (id, name) VALUES (105, 'Theresa Wright');
INSERT INTO public.authors (id, name) VALUES (106, 'George Smoot');
INSERT INTO public.authors (id, name) VALUES (107, 'Keay Davidson');
INSERT INTO public.authors (id, name) VALUES (108, 'Madeleine L''Engle');
INSERT INTO public.authors (id, name) VALUES (109, 'Tara MacCarthy');
INSERT INTO public.authors (id, name) VALUES (110, 'Cynthia Harrod-Eagles');
INSERT INTO public.authors (id, name) VALUES (111, 'Charles Todd');
INSERT INTO public.authors (id, name) VALUES (112, 'Ewan McGregor');
INSERT INTO public.authors (id, name) VALUES (113, 'Charley Boorman');
INSERT INTO public.authors (id, name) VALUES (114, 'Robert Uhlig');
INSERT INTO public.authors (id, name) VALUES (115, 'Daniel Abraham');
INSERT INTO public.authors (id, name) VALUES (116, 'Charles Willeford');
INSERT INTO public.authors (id, name) VALUES (117, 'James Lee Burke');
INSERT INTO public.authors (id, name) VALUES (118, 'Lawrence Block');
INSERT INTO public.authors (id, name) VALUES (119, 'Elmore Leonard');
INSERT INTO public.authors (id, name) VALUES (120, 'Tom Wolfe');
INSERT INTO public.authors (id, name) VALUES (121, 'Quentin Blake');
INSERT INTO public.authors (id, name) VALUES (122, 'Henry Miller');
INSERT INTO public.authors (id, name) VALUES (123, 'Thomas H. Moore');
INSERT INTO public.authors (id, name) VALUES (124, 'Ji??­ N?­l');
INSERT INTO public.authors (id, name) VALUES (125, 'Henry James');
INSERT INTO public.authors (id, name) VALUES (126, 'Patricia Crick');
INSERT INTO public.authors (id, name) VALUES (127, 'Gabriel Brownstein');
INSERT INTO public.authors (id, name) VALUES (128, 'Mary Cregan');
INSERT INTO public.authors (id, name) VALUES (129, 'Marguerite Duras');
INSERT INTO public.authors (id, name) VALUES (130, 'Barbara Bray');
INSERT INTO public.authors (id, name) VALUES (131, 'Richard Seever');
INSERT INTO public.authors (id, name) VALUES (132, 'Kahlil Gibran');
INSERT INTO public.authors (id, name) VALUES (133, 'Suheil Bushrui');
INSERT INTO public.authors (id, name) VALUES (134, 'Salma H. Al-Kuzbari');
INSERT INTO public.authors (id, name) VALUES (135, 'Jean Gibran');
INSERT INTO public.authors (id, name) VALUES (136, '?¬?¨?±?§? ?®??? ?¬?¨?±?§?');
INSERT INTO public.authors (id, name) VALUES (137, 'John Walbridge');
INSERT INTO public.authors (id, name) VALUES (138, 'Robin Waterfield');
INSERT INTO public.authors (id, name) VALUES (139, 'Anthony Rizcallah Ferris');
INSERT INTO public.authors (id, name) VALUES (140, 'Robert Louis Stevenson');
INSERT INTO public.authors (id, name) VALUES (141, 'Scott McKowen');
INSERT INTO public.authors (id, name) VALUES (142, 'N.C. Wyeth');
INSERT INTO public.authors (id, name) VALUES (143, 'Timothy Meis');
INSERT INTO public.authors (id, name) VALUES (144, 'Milo Winter');
INSERT INTO public.authors (id, name) VALUES (145, 'Deidre S. Laiken');
INSERT INTO public.authors (id, name) VALUES (146, 'A.J. McAllister');
INSERT INTO public.authors (id, name) VALUES (147, 'Ralph Ginzburg');
INSERT INTO public.authors (id, name) VALUES (148, 'Gabriel Garc?­a M??rquez');
INSERT INTO public.authors (id, name) VALUES (149, 'Dr. Seuss');
INSERT INTO public.authors (id, name) VALUES (150, 'Debbie Raleigh');
INSERT INTO public.authors (id, name) VALUES (151, 'Kevin Henkes');
INSERT INTO public.authors (id, name) VALUES (152, 'Patrick S??skind');
INSERT INTO public.authors (id, name) VALUES (153, 'Robert A. Heinlein');
INSERT INTO public.authors (id, name) VALUES (154, 'Nick  Webb');
INSERT INTO public.authors (id, name) VALUES (155, 'Terry Jones');
INSERT INTO public.authors (id, name) VALUES (156, 'Christopher Cerf');
INSERT INTO public.authors (id, name) VALUES (157, 'Susan Nanus');
INSERT INTO public.authors (id, name) VALUES (158, 'Norton Juster');
INSERT INTO public.authors (id, name) VALUES (159, 'Harry G. Frankfurt');
INSERT INTO public.authors (id, name) VALUES (160, 'Nick Flynn');
INSERT INTO public.authors (id, name) VALUES (161, 'Garry Wills');
INSERT INTO public.authors (id, name) VALUES (162, 'Abraham Lincoln');
INSERT INTO public.authors (id, name) VALUES (163, 'Michael McCurdy');
INSERT INTO public.authors (id, name) VALUES (164, 'Don DeLillo');
INSERT INTO public.authors (id, name) VALUES (165, 'Thomas Pynchon');
INSERT INTO public.authors (id, name) VALUES (166, 'Christophe Claro');
INSERT INTO public.authors (id, name) VALUES (167, 'Brice Matthieussent');
INSERT INTO public.authors (id, name) VALUES (168, 'Richard Fari?±a');
INSERT INTO public.authors (id, name) VALUES (169, 'Joan Didion');
INSERT INTO public.authors (id, name) VALUES (170, 'John Leonard');
INSERT INTO public.authors (id, name) VALUES (171, 'David Thomson');
INSERT INTO public.authors (id, name) VALUES (172, 'Paul Auster');
INSERT INTO public.authors (id, name) VALUES (173, 'Art Spiegelman');
INSERT INTO public.authors (id, name) VALUES (174, 'Luc Sante');
INSERT INTO public.authors (id, name) VALUES (175, 'Peter Moon');
INSERT INTO public.authors (id, name) VALUES (176, 'Preston B. Nichols');
INSERT INTO public.authors (id, name) VALUES (177, 'Nina Helms');
INSERT INTO public.authors (id, name) VALUES (178, 'Jared Diamond');
INSERT INTO public.authors (id, name) VALUES (179, 'Stephen Leeb');
INSERT INTO public.authors (id, name) VALUES (180, 'Glen C. Strathy');
INSERT INTO public.authors (id, name) VALUES (181, 'Joseph A. Tainter');
INSERT INTO public.authors (id, name) VALUES (182, 'Robert D. Putnam');
INSERT INTO public.authors (id, name) VALUES (183, 'Philip K. Howard');
INSERT INTO public.authors (id, name) VALUES (184, 'Joy Harjo');
INSERT INTO public.authors (id, name) VALUES (185, 'Gloria Bird');
INSERT INTO public.authors (id, name) VALUES (186, 'Beth Cuthand');
INSERT INTO public.authors (id, name) VALUES (187, 'Valerie Martinez');
INSERT INTO public.authors (id, name) VALUES (188, 'Patricia Blanco');
INSERT INTO public.authors (id, name) VALUES (189, 'Nikola Tesla');
INSERT INTO public.authors (id, name) VALUES (190, 'Marc J.  Seifer');
INSERT INTO public.authors (id, name) VALUES (191, 'William H. Terbo');
INSERT INTO public.authors (id, name) VALUES (192, 'Carol Dommermuth-Costa');
INSERT INTO public.authors (id, name) VALUES (193, 'David Hatcher Childress');
INSERT INTO public.authors (id, name) VALUES (194, 'Julie Elizabeth Leto');
INSERT INTO public.authors (id, name) VALUES (195, 'Leslie Kelly');
INSERT INTO public.authors (id, name) VALUES (196, 'Kimberly Raye');
INSERT INTO public.authors (id, name) VALUES (197, 'Chad Fowler');
INSERT INTO public.authors (id, name) VALUES (198, 'Andy Hunt');
INSERT INTO public.authors (id, name) VALUES (199, 'Maureen Kelly');
INSERT INTO public.authors (id, name) VALUES (200, 'CliffsNotes');
INSERT INTO public.authors (id, name) VALUES (201, 'William Golding');
INSERT INTO public.authors (id, name) VALUES (202, 'Victor Davis Hanson');
INSERT INTO public.authors (id, name) VALUES (203, 'Ephraim Sevela');
INSERT INTO public.authors (id, name) VALUES (204, 'Antonina W. Bouis');
INSERT INTO public.authors (id, name) VALUES (205, 'Alice Sebold');
INSERT INTO public.authors (id, name) VALUES (206, 'Sharyn McCrumb');
INSERT INTO public.authors (id, name) VALUES (207, 'Dave Shea');
INSERT INTO public.authors (id, name) VALUES (208, 'Molly E. Holzschlag');
INSERT INTO public.authors (id, name) VALUES (209, 'Elizabeth Castro');
INSERT INTO public.authors (id, name) VALUES (210, 'Michael Ochs');
INSERT INTO public.authors (id, name) VALUES (211, 'Patrick Javault');
INSERT INTO public.authors (id, name) VALUES (212, 'Ulrike Wasel');
INSERT INTO public.authors (id, name) VALUES (213, 'Chuck Klosterman');
INSERT INTO public.authors (id, name) VALUES (214, 'Jane Feather');
INSERT INTO public.authors (id, name) VALUES (215, 'Robert M. Pirsig');
INSERT INTO public.authors (id, name) VALUES (216, 'Kevin O''Malley');
INSERT INTO public.authors (id, name) VALUES (217, 'Carol Heyer');
INSERT INTO public.authors (id, name) VALUES (218, 'Scott Goto');
INSERT INTO public.authors (id, name) VALUES (219, 'Ronald L. DiSanto');
INSERT INTO public.authors (id, name) VALUES (220, 'Thomas J. Steele');
INSERT INTO public.authors (id, name) VALUES (221, 'John Harold Haynes');
INSERT INTO public.authors (id, name) VALUES (222, 'Catharine M. Fishel');
INSERT INTO public.authors (id, name) VALUES (223, 'Bill Gardner');
INSERT INTO public.authors (id, name) VALUES (224, 'Hugh McLean');
INSERT INTO public.authors (id, name) VALUES (225, 'Ayn Rand');
INSERT INTO public.authors (id, name) VALUES (226, 'Leonard Peikoff');
INSERT INTO public.authors (id, name) VALUES (227, 'Nathaniel Branden');
INSERT INTO public.authors (id, name) VALUES (228, 'Alan Greenspan');
INSERT INTO public.authors (id, name) VALUES (229, 'Robert Hessen');
INSERT INTO public.authors (id, name) VALUES (230, 'Michael S. Berliner');
INSERT INTO public.authors (id, name) VALUES (231, 'J.J. Isler');
INSERT INTO public.authors (id, name) VALUES (232, 'Peter Isler');
INSERT INTO public.authors (id, name) VALUES (233, 'Colin  Wells');
INSERT INTO public.authors (id, name) VALUES (234, 'Billy Collins');
INSERT INTO public.authors (id, name) VALUES (235, 'Christopher Caswell');
INSERT INTO public.authors (id, name) VALUES (236, 'Kevin Trudeau');
INSERT INTO public.authors (id, name) VALUES (237, 'Bernard Malamud');
INSERT INTO public.authors (id, name) VALUES (238, 'Kevin Baker');
INSERT INTO public.authors (id, name) VALUES (239, 'Anne Tyler');
INSERT INTO public.authors (id, name) VALUES (240, 'Gary Colombo');
INSERT INTO public.authors (id, name) VALUES (241, 'Bonnie Lisle');
INSERT INTO public.authors (id, name) VALUES (242, 'Thomas E. Skidmore');
INSERT INTO public.authors (id, name) VALUES (243, 'Peter H. Smith');
INSERT INTO public.authors (id, name) VALUES (244, 'Philip Roth');
INSERT INTO public.authors (id, name) VALUES (245, 'Jon   Stewart');
INSERT INTO public.authors (id, name) VALUES (246, 'Edith Grossman');
INSERT INTO public.authors (id, name) VALUES (247, 'Brian Greene');
INSERT INTO public.authors (id, name) VALUES (248, 'Upasika Kee Nanayon');
INSERT INTO public.authors (id, name) VALUES (249, 'Thanissaro Bhikkhu');
INSERT INTO public.authors (id, name) VALUES (250, 'Rob Humphreys');
INSERT INTO public.authors (id, name) VALUES (251, 'Beth Chaplin');
INSERT INTO public.authors (id, name) VALUES (252, 'Rebecca Morrill');
INSERT INTO public.authors (id, name) VALUES (253, 'Lonely Planet');
INSERT INTO public.authors (id, name) VALUES (254, 'Sarah Johnstone');
INSERT INTO public.authors (id, name) VALUES (255, 'Steve Fallon');
INSERT INTO public.authors (id, name) VALUES (256, 'Tom Masters');
INSERT INTO public.authors (id, name) VALUES (257, 'Mark Honan');
INSERT INTO public.authors (id, name) VALUES (258, 'H.G. Bissinger');
INSERT INTO public.authors (id, name) VALUES (259, 'Neal Stephenson');
INSERT INTO public.authors (id, name) VALUES (260, 'J. Frederick George');
INSERT INTO public.authors (id, name) VALUES (261, 'Pedro Jorge Romero');
INSERT INTO public.authors (id, name) VALUES (262, 'George F. Jewsbury');
INSERT INTO public.authors (id, name) VALUES (263, 'Stephen  Bury');
INSERT INTO public.authors (id, name) VALUES (264, 'Guy Abadia');
INSERT INTO public.authors (id, name) VALUES (265, 'Dan Harrington');
INSERT INTO public.authors (id, name) VALUES (266, 'Bill Robertie');
INSERT INTO public.authors (id, name) VALUES (267, 'Donald A. Norman');
INSERT INTO public.authors (id, name) VALUES (268, 'Alex C. Jones');
INSERT INTO public.authors (id, name) VALUES (269, 'Diane M. Hanson');
INSERT INTO public.authors (id, name) VALUES (270, 'Stephen K. Ray');
INSERT INTO public.authors (id, name) VALUES (271, 'Paulo Coelho');
INSERT INTO public.authors (id, name) VALUES (272, 'Alan R. Clarke');
INSERT INTO public.authors (id, name) VALUES (273, 'James Noel Smith');
INSERT INTO public.authors (id, name) VALUES (274, '?zdemir Ä°nce');
INSERT INTO public.authors (id, name) VALUES (275, 'Hiromu Arakawa');
INSERT INTO public.authors (id, name) VALUES (276, 'Akira Watanabe');
INSERT INTO public.authors (id, name) VALUES (277, 'M?bius');
INSERT INTO public.authors (id, name) VALUES (278, 'Robert   Harris');
INSERT INTO public.authors (id, name) VALUES (279, 'Edward Bulwer-Lytton');
INSERT INTO public.authors (id, name) VALUES (280, 'John Gregory Betancourt');
INSERT INTO public.authors (id, name) VALUES (281, 'John Steinbeck');
INSERT INTO public.authors (id, name) VALUES (282, 'Neil Strauss');
INSERT INTO public.authors (id, name) VALUES (283, 'Ellen Raskin');
INSERT INTO public.authors (id, name) VALUES (284, 'Arthur Golden');
INSERT INTO public.authors (id, name) VALUES (285, 'David        James');
INSERT INTO public.authors (id, name) VALUES (286, 'Peggy Mulloy');
INSERT INTO public.authors (id, name) VALUES (287, 'Rob Marshall');
INSERT INTO public.authors (id, name) VALUES (288, 'Mineko Iwasaki');
INSERT INTO public.authors (id, name) VALUES (289, 'Rande Brown');
INSERT INTO public.authors (id, name) VALUES (290, 'J. Torres');
INSERT INTO public.authors (id, name) VALUES (291, 'Eric  Kim');
INSERT INTO public.authors (id, name) VALUES (292, 'Margaret Johnson');
INSERT INTO public.authors (id, name) VALUES (293, 'Philip Prowse');
INSERT INTO public.authors (id, name) VALUES (294, 'Gary Chapman');
INSERT INTO public.authors (id, name) VALUES (295, 'Dan Brown');
INSERT INTO public.authors (id, name) VALUES (296, 'Ra??l Amundaray');
INSERT INTO public.authors (id, name) VALUES (297, 'Daniel Roche');
INSERT INTO public.authors (id, name) VALUES (298, 'P.J. Parrish');
INSERT INTO public.authors (id, name) VALUES (299, 'Thomas J. Stanley');
INSERT INTO public.authors (id, name) VALUES (300, 'William D. Danko');
INSERT INTO public.authors (id, name) VALUES (301, 'Napoleon Hill');
INSERT INTO public.authors (id, name) VALUES (302, 'Mike   Mason');
INSERT INTO public.authors (id, name) VALUES (303, 'Riki Anne Wilchins');
INSERT INTO public.authors (id, name) VALUES (304, 'Donald J. Trump');
INSERT INTO public.authors (id, name) VALUES (305, 'Tony Schwartz');
INSERT INTO public.authors (id, name) VALUES (306, 'George S. Clason');
INSERT INTO public.authors (id, name) VALUES (307, 'Trevanian');
INSERT INTO public.authors (id, name) VALUES (308, 'Gisela Stege');
INSERT INTO public.authors (id, name) VALUES (309, 'David McCullough');
INSERT INTO public.authors (id, name) VALUES (310, 'Peter  Stone');
INSERT INTO public.authors (id, name) VALUES (311, 'Sherman Edwards');
INSERT INTO public.authors (id, name) VALUES (312, 'Robert J. Allison');
INSERT INTO public.authors (id, name) VALUES (313, 'Pearl S. Buck');
INSERT INTO public.authors (id, name) VALUES (314, 'Rick Warren');
INSERT INTO public.authors (id, name) VALUES (315, 'Eric Schlosser');
INSERT INTO public.authors (id, name) VALUES (316, 'Lisa See');
INSERT INTO public.authors (id, name) VALUES (317, 'John Grisham');
INSERT INTO public.authors (id, name) VALUES (318, 'Robert A. Caro');
INSERT INTO public.authors (id, name) VALUES (319, 'Stephen W. Frey');
INSERT INTO public.authors (id, name) VALUES (320, 'Bill Phillips');
INSERT INTO public.authors (id, name) VALUES (321, 'Michael D''Orso');
INSERT INTO public.authors (id, name) VALUES (322, 'Pamela Peeke');
INSERT INTO public.authors (id, name) VALUES (323, 'Cindy Crawford');
INSERT INTO public.authors (id, name) VALUES (324, 'Robert G. Hagstrom');
INSERT INTO public.authors (id, name) VALUES (325, 'Bill Miller');
INSERT INTO public.authors (id, name) VALUES (326, 'Kenneth L. Fisher');
INSERT INTO public.authors (id, name) VALUES (327, 'Robert P. Miles');
INSERT INTO public.authors (id, name) VALUES (328, 'Tom Osborne');
INSERT INTO public.authors (id, name) VALUES (329, 'Marvin N. Olasky');
INSERT INTO public.authors (id, name) VALUES (330, 'John R. Perry');
INSERT INTO public.authors (id, name) VALUES (331, 'Barbara Park');
INSERT INTO public.authors (id, name) VALUES (332, 'Denise Brunkus');
INSERT INTO public.authors (id, name) VALUES (333, 'Sarah Mlynowski');
INSERT INTO public.authors (id, name) VALUES (334, 'Michael   Lewis');
INSERT INTO public.authors (id, name) VALUES (335, 'Frank McConnell');
INSERT INTO public.authors (id, name) VALUES (336, 'Ursula Ferrigno');
INSERT INTO public.authors (id, name) VALUES (337, 'Jason Lowe');
INSERT INTO public.authors (id, name) VALUES (338, 'Maxine  Clark');
INSERT INTO public.authors (id, name) VALUES (339, 'Giada De Laurentiis');
INSERT INTO public.authors (id, name) VALUES (340, 'Victoria Pearson');
INSERT INTO public.authors (id, name) VALUES (341, 'Tyler Florence');
INSERT INTO public.authors (id, name) VALUES (342, 'Petrina Tinslay');
INSERT INTO public.authors (id, name) VALUES (343, 'JoAnn Cianciulli');
INSERT INTO public.authors (id, name) VALUES (344, 'Bill Bettencourt');
INSERT INTO public.authors (id, name) VALUES (345, 'Bobby Flay');
INSERT INTO public.authors (id, name) VALUES (346, 'Steven D. Levitt');
INSERT INTO public.authors (id, name) VALUES (347, 'Stephen J. Dubner');
INSERT INTO public.authors (id, name) VALUES (348, 'Barry Eisler');
INSERT INTO public.authors (id, name) VALUES (349, 'Yann Martel');
INSERT INTO public.authors (id, name) VALUES (350, 'Nicole Martel');
INSERT INTO public.authors (id, name) VALUES (351, 'Emile Martel');
INSERT INTO public.authors (id, name) VALUES (352, 'Robert Templer');
INSERT INTO public.authors (id, name) VALUES (353, 'James Frey');
INSERT INTO public.authors (id, name) VALUES (354, 'Python Bonkers');
INSERT INTO public.authors (id, name) VALUES (355, 'James Pinocchio');
INSERT INTO public.authors (id, name) VALUES (356, 'Pablo Fenjves');
INSERT INTO public.authors (id, name) VALUES (357, 'James M. Kouzes');
INSERT INTO public.authors (id, name) VALUES (358, 'Barry Z. Posner');
INSERT INTO public.authors (id, name) VALUES (359, 'Donald T. Phillips');
INSERT INTO public.authors (id, name) VALUES (360, 'Gary Yukl');
INSERT INTO public.authors (id, name) VALUES (361, 'Rudolph W. Giuliani');
INSERT INTO public.authors (id, name) VALUES (362, 'John Gray');
INSERT INTO public.authors (id, name) VALUES (363, 'Ron  Louis');
INSERT INTO public.authors (id, name) VALUES (364, 'David Copeland');
INSERT INTO public.authors (id, name) VALUES (365, 'Jean M. Auel');
INSERT INTO public.authors (id, name) VALUES (366, 'Doug Walsh');
INSERT INTO public.authors (id, name) VALUES (367, 'Steven Pressfield');
INSERT INTO public.authors (id, name) VALUES (368, 'Margaret Weis');
INSERT INTO public.authors (id, name) VALUES (369, 'Tracy Hickman');
INSERT INTO public.authors (id, name) VALUES (370, 'Thomas Harlan');
INSERT INTO public.authors (id, name) VALUES (371, 'Robert McKee');
INSERT INTO public.authors (id, name) VALUES (372, 'Stephen J. Rosen');
INSERT INTO public.authors (id, name) VALUES (373, 'David J. Danelo');
INSERT INTO public.authors (id, name) VALUES (374, 'Plato');
INSERT INTO public.authors (id, name) VALUES (375, 'Walter Hamilton');
INSERT INTO public.authors (id, name) VALUES (376, 'C.J. Rowe');
INSERT INTO public.authors (id, name) VALUES (377, 'Benjamin Jowett');
INSERT INTO public.authors (id, name) VALUES (378, 'Josef Pieper');
INSERT INTO public.authors (id, name) VALUES (379, 'Richard Winston');
INSERT INTO public.authors (id, name) VALUES (380, 'Clara Winston');
INSERT INTO public.authors (id, name) VALUES (381, 'C.D.C. Reeve');
INSERT INTO public.authors (id, name) VALUES (382, 'James H. Nichols Jr.');
INSERT INTO public.authors (id, name) VALUES (383, 'Chris Emlyn-Jones');
INSERT INTO public.authors (id, name) VALUES (384, 'Herodotus');
INSERT INTO public.authors (id, name) VALUES (385, 'Aubrey de S?©lincourt');
INSERT INTO public.authors (id, name) VALUES (386, 'John M. Marincola');
INSERT INTO public.authors (id, name) VALUES (387, 'Henry Francis Cary');
INSERT INTO public.authors (id, name) VALUES (388, 'Carolyn Dewald');
INSERT INTO public.authors (id, name) VALUES (389, 'Andrew Robert Burn');
INSERT INTO public.authors (id, name) VALUES (390, 'Jennifer Tolbert Roberts');
INSERT INTO public.authors (id, name) VALUES (391, 'Walter Blanco');
INSERT INTO public.authors (id, name) VALUES (392, 'Edward Henry Blakeney');
INSERT INTO public.authors (id, name) VALUES (393, 'George Rawlinson');
INSERT INTO public.authors (id, name) VALUES (394, 'Rosalind Thomas');
INSERT INTO public.authors (id, name) VALUES (395, 'Peter Grene');
INSERT INTO public.authors (id, name) VALUES (396, 'Homer');
INSERT INTO public.authors (id, name) VALUES (397, 'Robert Fagles');
INSERT INTO public.authors (id, name) VALUES (398, 'Bernard Knox');
INSERT INTO public.authors (id, name) VALUES (399, 'Stanley Lombardo');
INSERT INTO public.authors (id, name) VALUES (400, 'Sheila Murnaghan');
INSERT INTO public.authors (id, name) VALUES (401, 'Robert Fitzgerald');
INSERT INTO public.authors (id, name) VALUES (402, 'Andrew Ford');
INSERT INTO public.authors (id, name) VALUES (403, 'E.V. Rieu');
INSERT INTO public.authors (id, name) VALUES (404, 'Peter Jones');
INSERT INTO public.authors (id, name) VALUES (405, 'D.C.H. Rieu');
INSERT INTO public.authors (id, name) VALUES (406, 'W.H.D. Rouse');
INSERT INTO public.authors (id, name) VALUES (407, 'Virgil');
INSERT INTO public.authors (id, name) VALUES (408, 'Barbara Weiden Boyd');
INSERT INTO public.authors (id, name) VALUES (409, 'Henry Rushton Fairclough');
INSERT INTO public.authors (id, name) VALUES (410, 'G.P. Goold');
INSERT INTO public.authors (id, name) VALUES (411, 'Ed Roberson');
INSERT INTO public.authors (id, name) VALUES (412, 'Cecil Day-Lewis');
INSERT INTO public.authors (id, name) VALUES (413, 'Paul  Kirk');
INSERT INTO public.authors (id, name) VALUES (414, 'William Shakespeare');
INSERT INTO public.authors (id, name) VALUES (415, 'Stephen Orgel');
INSERT INTO public.authors (id, name) VALUES (416, 'A.R. Braunmuller');
INSERT INTO public.authors (id, name) VALUES (417, 'Harold Bloom');
INSERT INTO public.authors (id, name) VALUES (418, 'Rex Gibson');
INSERT INTO public.authors (id, name) VALUES (419, 'Reduced Shakespeare Company');
INSERT INTO public.authors (id, name) VALUES (420, 'Adam Long');
INSERT INTO public.authors (id, name) VALUES (421, 'Daniel Singer');
INSERT INTO public.authors (id, name) VALUES (422, 'Jess Winfield');
INSERT INTO public.authors (id, name) VALUES (423, 'Margaret Jull Costa');
INSERT INTO public.authors (id, name) VALUES (424, 'Clifford E. Landers');
INSERT INTO public.authors (id, name) VALUES (425, 'K??muran ?ipal');
INSERT INTO public.authors (id, name) VALUES (426, 'Carla Lynn Stockton');
INSERT INTO public.authors (id, name) VALUES (427, 'Terri Mategrano');
INSERT INTO public.authors (id, name) VALUES (428, 'Thucydides');
INSERT INTO public.authors (id, name) VALUES (429, 'C.F. Smith');
INSERT INTO public.authors (id, name) VALUES (430, 'Paul Woodruff');
INSERT INTO public.authors (id, name) VALUES (431, 'Steven Lattimore');
INSERT INTO public.authors (id, name) VALUES (432, 'Cynthia W. Shelmerdine');
INSERT INTO public.authors (id, name) VALUES (433, 'Euripides');
INSERT INTO public.authors (id, name) VALUES (434, 'Richmond Lattimore');
INSERT INTO public.authors (id, name) VALUES (435, 'David Grene');
INSERT INTO public.authors (id, name) VALUES (436, 'Rex Warner');
INSERT INTO public.authors (id, name) VALUES (437, 'Ralph Gladstone');
INSERT INTO public.authors (id, name) VALUES (438, 'Emily Townsend Vermeule');
INSERT INTO public.authors (id, name) VALUES (439, 'Elizabeth Wyckoff');
INSERT INTO public.authors (id, name) VALUES (440, 'William Arrowsmith');
INSERT INTO public.authors (id, name) VALUES (441, 'Frank William Jones');
INSERT INTO public.authors (id, name) VALUES (442, 'Charles R. Walker');
INSERT INTO public.authors (id, name) VALUES (443, 'Anne Carson');
INSERT INTO public.authors (id, name) VALUES (444, 'Moses Hadas');
INSERT INTO public.authors (id, name) VALUES (445, 'John Maclean');
INSERT INTO public.authors (id, name) VALUES (446, 'John Frederick Nims');
INSERT INTO public.authors (id, name) VALUES (447, 'Ronald Frederick Willetts');
INSERT INTO public.authors (id, name) VALUES (448, 'Witter Bynner');
INSERT INTO public.authors (id, name) VALUES (449, 'John Davie');
INSERT INTO public.authors (id, name) VALUES (450, 'Richard Rutherford');
INSERT INTO public.authors (id, name) VALUES (451, 'David Kovacs');
INSERT INTO public.authors (id, name) VALUES (452, 'Donald J. Mastronarde');
INSERT INTO public.authors (id, name) VALUES (453, 'Reginald Gibbons');
INSERT INTO public.authors (id, name) VALUES (454, 'Peter H. Burian');
INSERT INTO public.authors (id, name) VALUES (455, 'David Thompson');
INSERT INTO public.authors (id, name) VALUES (456, 'J. Michael Walton');
INSERT INTO public.authors (id, name) VALUES (457, 'Wole Soyinka');
INSERT INTO public.authors (id, name) VALUES (458, 'James Morwood');
INSERT INTO public.authors (id, name) VALUES (459, 'Georgia Ann Machemer');
INSERT INTO public.authors (id, name) VALUES (460, 'Michael   Collier');
INSERT INTO public.authors (id, name) VALUES (461, 'William Allan');
INSERT INTO public.authors (id, name) VALUES (462, 'Robert J. Milch');
INSERT INTO public.authors (id, name) VALUES (463, 'Pantelis Michelakis');
INSERT INTO public.authors (id, name) VALUES (464, 'Aeschylus');
INSERT INTO public.authors (id, name) VALUES (465, 'Seth Benardete');
INSERT INTO public.authors (id, name) VALUES (466, 'Alan Shapiro');
INSERT INTO public.authors (id, name) VALUES (467, 'William Bedell Stanford');
INSERT INTO public.authors (id, name) VALUES (468, 'Peter Meineck');
INSERT INTO public.authors (id, name) VALUES (469, 'Helene P. Foley');
INSERT INTO public.authors (id, name) VALUES (470, 'Philip Vellacott');
INSERT INTO public.authors (id, name) VALUES (471, 'Ted Hughes');
INSERT INTO public.authors (id, name) VALUES (472, 'David R. Slavitt');
INSERT INTO public.authors (id, name) VALUES (473, 'Smith Palmer Bovie');
INSERT INTO public.authors (id, name) VALUES (474, 'Simon Goldhill');
INSERT INTO public.authors (id, name) VALUES (475, 'George Thomson');
INSERT INTO public.authors (id, name) VALUES (476, 'Richard Seaford');
INSERT INTO public.authors (id, name) VALUES (477, 'E.D.A. Morshead');
INSERT INTO public.authors (id, name) VALUES (478, 'Sophocles');
INSERT INTO public.authors (id, name) VALUES (479, 'John Moore');
INSERT INTO public.authors (id, name) VALUES (480, 'Michael Jameson');
INSERT INTO public.authors (id, name) VALUES (481, 'Paul Roche');
INSERT INTO public.authors (id, name) VALUES (482, 'Dudley Fitts');
INSERT INTO public.authors (id, name) VALUES (483, 'Charles Segal');
INSERT INTO public.authors (id, name) VALUES (484, 'E.F. Watling');
INSERT INTO public.authors (id, name) VALUES (485, 'J.E. Thomas');
INSERT INTO public.authors (id, name) VALUES (486, 'Roger D. Dawe');
INSERT INTO public.authors (id, name) VALUES (487, 'Cynthia Brantley Johnson');
INSERT INTO public.authors (id, name) VALUES (488, 'Aristophanes');
INSERT INTO public.authors (id, name) VALUES (489, 'Douglass Parker');
INSERT INTO public.authors (id, name) VALUES (490, 'Jeffrey Henderson');
INSERT INTO public.authors (id, name) VALUES (491, 'Alan H. Sommerstein');
INSERT INTO public.authors (id, name) VALUES (492, 'Kenneth James Dover');
INSERT INTO public.authors (id, name) VALUES (493, 'David B. Barrett');
INSERT INTO public.authors (id, name) VALUES (494, 'W. John Campbell');
INSERT INTO public.authors (id, name) VALUES (495, 'Douglas M. MacDowell');
INSERT INTO public.authors (id, name) VALUES (496, 'S. Douglas Olson');
INSERT INTO public.authors (id, name) VALUES (497, 'Sarah Ruden');
INSERT INTO public.authors (id, name) VALUES (498, 'David Brett');
INSERT INTO public.authors (id, name) VALUES (499, 'Andrea Wilson Nightingale');
INSERT INTO public.authors (id, name) VALUES (500, 'Mark Haddon');
INSERT INTO public.authors (id, name) VALUES (501, 'George Pelecanos');
INSERT INTO public.authors (id, name) VALUES (502, 'Annie Proulx');
INSERT INTO public.authors (id, name) VALUES (503, 'David    Allen');
INSERT INTO public.authors (id, name) VALUES (504, 'Geoffrey M. Bellman');
INSERT INTO public.authors (id, name) VALUES (505, 'Ricardo Piglia');
INSERT INTO public.authors (id, name) VALUES (506, 'Amanda Hopkinson');
INSERT INTO public.authors (id, name) VALUES (507, 'Karen  O''Connor');
INSERT INTO public.authors (id, name) VALUES (508, 'Larry J. Sabato');
INSERT INTO public.authors (id, name) VALUES (509, 'Ernesto Sabato');
INSERT INTO public.authors (id, name) VALUES (510, 'Augustine of Hippo');
INSERT INTO public.authors (id, name) VALUES (511, 'John E. Rotelle');
INSERT INTO public.authors (id, name) VALUES (512, 'Maria Boulding');
INSERT INTO public.authors (id, name) VALUES (513, 'Thomas Merton');
INSERT INTO public.authors (id, name) VALUES (514, 'Marcus Dods');
INSERT INTO public.authors (id, name) VALUES (515, 'Bruce Harbert');
INSERT INTO public.authors (id, name) VALUES (516, 'Peter R.L. Brown');
INSERT INTO public.authors (id, name) VALUES (517, 'D.W. Robertson Jr.');
INSERT INTO public.authors (id, name) VALUES (518, 'Frank Sheed');
INSERT INTO public.authors (id, name) VALUES (519, 'Henry Chadwick');
INSERT INTO public.authors (id, name) VALUES (520, 'Boniface Ramsey');
INSERT INTO public.authors (id, name) VALUES (521, 'Edmund Hill');
INSERT INTO public.authors (id, name) VALUES (522, 'Anthony Bourdain');
INSERT INTO public.authors (id, name) VALUES (523, 'Ovid');
INSERT INTO public.authors (id, name) VALUES (524, 'Allen Mandelbaum');
INSERT INTO public.authors (id, name) VALUES (525, 'David Raeburn');
INSERT INTO public.authors (id, name) VALUES (526, 'Denis Feeney');
INSERT INTO public.authors (id, name) VALUES (527, 'Charles    Martin');
INSERT INTO public.authors (id, name) VALUES (528, 'William Scovil Anderson');
INSERT INTO public.authors (id, name) VALUES (529, 'Norma Goldman');
INSERT INTO public.authors (id, name) VALUES (530, 'Jacob E. Nyenhuis');
INSERT INTO public.authors (id, name) VALUES (531, 'J.H. Mozley');
INSERT INTO public.authors (id, name) VALUES (532, 'Peter Green');
INSERT INTO public.authors (id, name) VALUES (533, 'Frank Justus Miller');
INSERT INTO public.authors (id, name) VALUES (534, 'Michael  Rossi');
INSERT INTO public.authors (id, name) VALUES (535, 'Michael C.J. Putnam');
INSERT INTO public.authors (id, name) VALUES (536, 'Richard Johnsonbaugh');
INSERT INTO public.authors (id, name) VALUES (537, 'Martin Kalin');
INSERT INTO public.authors (id, name) VALUES (538, 'Daniel Pinchbeck');
INSERT INTO public.authors (id, name) VALUES (539, 'Jon Ronson');
INSERT INTO public.authors (id, name) VALUES (540, 'Daniel Duane');
INSERT INTO public.authors (id, name) VALUES (541, 'Jon Krakauer');
INSERT INTO public.authors (id, name) VALUES (542, 'John Eldredge');
INSERT INTO public.authors (id, name) VALUES (543, 'Jung Chang');
INSERT INTO public.authors (id, name) VALUES (544, 'Nelson DeMille');
INSERT INTO public.authors (id, name) VALUES (545, 'Catherine Coulter');
INSERT INTO public.authors (id, name) VALUES (546, 'Jack London');
INSERT INTO public.authors (id, name) VALUES (547, 'Avi');
INSERT INTO public.authors (id, name) VALUES (548, 'Judy Sierra');
INSERT INTO public.authors (id, name) VALUES (549, 'Marc Brown');
INSERT INTO public.authors (id, name) VALUES (550, 'Charles P. Rubenstein');
INSERT INTO public.authors (id, name) VALUES (551, 'Barbara Ehrenreich');
INSERT INTO public.authors (id, name) VALUES (552, 'Michel Foucault');
INSERT INTO public.authors (id, name) VALUES (553, 'Robert Hurley');
INSERT INTO public.authors (id, name) VALUES (554, 'Sue Birtwistle');
INSERT INTO public.authors (id, name) VALUES (555, 'Sue Conklin');
INSERT INTO public.authors (id, name) VALUES (556, 'Susie Conklin');
INSERT INTO public.authors (id, name) VALUES (557, 'Jane Austen');
INSERT INTO public.authors (id, name) VALUES (558, 'Vivien Jones');
INSERT INTO public.authors (id, name) VALUES (559, 'George Saintsbury');
INSERT INTO public.authors (id, name) VALUES (560, 'Hugh  Thomson');
INSERT INTO public.authors (id, name) VALUES (561, 'Carol Howard');
INSERT INTO public.authors (id, name) VALUES (562, 'David  Roberts');
INSERT INTO public.authors (id, name) VALUES (563, 'Valerian Albanov');
INSERT INTO public.authors (id, name) VALUES (564, 'Alison Anderson');
INSERT INTO public.authors (id, name) VALUES (565, '??°?»?µ??¸?°?? ??»???±?°??????');
INSERT INTO public.authors (id, name) VALUES (566, 'Thomas L. Friedman');
INSERT INTO public.authors (id, name) VALUES (567, 'David McClung');
INSERT INTO public.authors (id, name) VALUES (568, 'Peter Schaerer');
INSERT INTO public.authors (id, name) VALUES (569, 'Arthur J. Roth');
INSERT INTO public.authors (id, name) VALUES (570, 'Louisa May Alcott');
INSERT INTO public.authors (id, name) VALUES (571, 'Paula Danziger');
INSERT INTO public.authors (id, name) VALUES (572, 'Jessie Willcox Smith');
INSERT INTO public.authors (id, name) VALUES (573, 'Frank T. Merrill');
INSERT INTO public.authors (id, name) VALUES (574, 'Elaine Showalter');
INSERT INTO public.authors (id, name) VALUES (575, 'Charles Dickens');
INSERT INTO public.authors (id, name) VALUES (576, 'Keith Cox');
INSERT INTO public.authors (id, name) VALUES (577, 'Gillen D''Arcy Wood');
INSERT INTO public.authors (id, name) VALUES (578, 'SparkNotes');
INSERT INTO public.authors (id, name) VALUES (579, 'Simon Schama');
INSERT INTO public.authors (id, name) VALUES (580, 'James B. Stewart');
INSERT INTO public.authors (id, name) VALUES (581, 'Julia Golding');
INSERT INTO public.authors (id, name) VALUES (582, 'Mary Gaitskill');
INSERT INTO public.authors (id, name) VALUES (583, 'Hablot Knight Browne');
INSERT INTO public.authors (id, name) VALUES (584, 'Gish Jen');
INSERT INTO public.authors (id, name) VALUES (585, 'Daniel Pool');
INSERT INTO public.authors (id, name) VALUES (586, 'Jane Smiley');
INSERT INTO public.authors (id, name) VALUES (587, 'Patricia Ingham');
INSERT INTO public.authors (id, name) VALUES (588, 'Colleen Sexton');
INSERT INTO public.authors (id, name) VALUES (589, 'Philip Nel');
INSERT INTO public.authors (id, name) VALUES (590, 'Sean O''Brien');
INSERT INTO public.authors (id, name) VALUES (591, 'B.B. Rogers');
INSERT INTO public.authors (id, name) VALUES (592, 'Radcliffe G. Edmonds III');
INSERT INTO public.authors (id, name) VALUES (593, 'Robert Mayhew');
INSERT INTO public.authors (id, name) VALUES (594, 'Paul Anthony Cartledge');
INSERT INTO public.authors (id, name) VALUES (595, 'Raymond Chandler');
INSERT INTO public.authors (id, name) VALUES (596, 'Frank MacShane');
INSERT INTO public.authors (id, name) VALUES (597, 'Paul Murray');
INSERT INTO public.authors (id, name) VALUES (598, 'Patti   Davis');
INSERT INTO public.authors (id, name) VALUES (599, 'Daniel C. Dennett');
INSERT INTO public.authors (id, name) VALUES (600, 'Nicholas Humphrey');
INSERT INTO public.authors (id, name) VALUES (601, 'Douglas R. Hofstadter');
INSERT INTO public.authors (id, name) VALUES (602, 'Stephen Hawking');
INSERT INTO public.authors (id, name) VALUES (603, 'Leonard Mlodinow');
INSERT INTO public.authors (id, name) VALUES (604, 'David Filkin');
INSERT INTO public.authors (id, name) VALUES (605, 'Kip S. Thorne');
INSERT INTO public.authors (id, name) VALUES (606, 'Igor Novikov');
INSERT INTO public.authors (id, name) VALUES (607, 'Timothy Ferris');
INSERT INTO public.authors (id, name) VALUES (608, 'Alan Lightman');
INSERT INTO public.authors (id, name) VALUES (609, 'Richard     Price');
INSERT INTO public.authors (id, name) VALUES (610, 'John Boslough');
INSERT INTO public.authors (id, name) VALUES (611, 'Roger Penrose');
INSERT INTO public.authors (id, name) VALUES (612, 'Lawrence M. Krauss');
INSERT INTO public.authors (id, name) VALUES (613, 'Phillip Glasier');
INSERT INTO public.authors (id, name) VALUES (614, 'Peter   Schwartz');
INSERT INTO public.authors (id, name) VALUES (615, 'David Harriman');
INSERT INTO public.authors (id, name) VALUES (616, 'Nancy L. Mace');
INSERT INTO public.authors (id, name) VALUES (617, 'Peter V. Rabins');
INSERT INTO public.authors (id, name) VALUES (618, 'Jorge Cruise');
INSERT INTO public.authors (id, name) VALUES (619, 'Thom Hartmann');
INSERT INTO public.authors (id, name) VALUES (620, 'Joseph Chilton Pearce');
INSERT INTO public.authors (id, name) VALUES (621, 'Neale Donald Walsch');
INSERT INTO public.authors (id, name) VALUES (622, 'Michael Cunningham');
INSERT INTO public.authors (id, name) VALUES (623, 'Malcolm Gladwell');
INSERT INTO public.authors (id, name) VALUES (624, 'Ted Dekker');
INSERT INTO public.authors (id, name) VALUES (625, 'Mark Hoppus');
INSERT INTO public.authors (id, name) VALUES (626, 'Anne Hoppus');
INSERT INTO public.authors (id, name) VALUES (627, 'Alex Gaskarth');
INSERT INTO public.authors (id, name) VALUES (628, 'Karen Joy Fowler');
INSERT INTO public.authors (id, name) VALUES (629, 'Deirdre Le Faye');
INSERT INTO public.authors (id, name) VALUES (630, 'James Kinsley');
INSERT INTO public.authors (id, name) VALUES (631, 'Anna Massey');
INSERT INTO public.authors (id, name) VALUES (632, 'Richard S. Hartmetz');
INSERT INTO public.authors (id, name) VALUES (633, 'Maurgaux Motin');
INSERT INTO public.authors (id, name) VALUES (634, 'Deidre Shauna Lynch');
INSERT INTO public.authors (id, name) VALUES (635, 'Kim Wilson');
INSERT INTO public.authors (id, name) VALUES (636, 'Tom Carpenter');
INSERT INTO public.authors (id, name) VALUES (637, 'Ernest Hemingway');
INSERT INTO public.authors (id, name) VALUES (638, 'Donald Sutherland');
INSERT INTO public.authors (id, name) VALUES (639, 'Jeanne Sallade Criswell');
INSERT INTO public.authors (id, name) VALUES (640, 'Gary Carey');
INSERT INTO public.authors (id, name) VALUES (641, 'Julian Barnes');
INSERT INTO public.authors (id, name) VALUES (642, 'Gustave Flaubert');
INSERT INTO public.authors (id, name) VALUES (643, 'Francis Steegmuller');
INSERT INTO public.authors (id, name) VALUES (644, 'Douglas Parm?©e');
INSERT INTO public.authors (id, name) VALUES (645, 'Roger Whitehouse');
INSERT INTO public.authors (id, name) VALUES (646, 'Geoffrey Wall');
INSERT INTO public.authors (id, name) VALUES (647, 'Robert Baldick');
INSERT INTO public.authors (id, name) VALUES (648, 'Jean-Paul Sartre');
INSERT INTO public.authors (id, name) VALUES (649, 'Carol Cosman');
INSERT INTO public.authors (id, name) VALUES (650, 'Jeffrey Eugenides');
INSERT INTO public.authors (id, name) VALUES (651, 'Doris Kearns Goodwin');
INSERT INTO public.authors (id, name) VALUES (652, 'Thomas May');
INSERT INTO public.authors (id, name) VALUES (653, 'John   Adams');
INSERT INTO public.authors (id, name) VALUES (654, 'Abigail Adams');
INSERT INTO public.authors (id, name) VALUES (655, 'Frank Shuffelton');
INSERT INTO public.authors (id, name) VALUES (656, 'Joseph J. Ellis');
INSERT INTO public.authors (id, name) VALUES (657, 'John  Adams');
INSERT INTO public.authors (id, name) VALUES (658, 'John Patrick Diggins');
INSERT INTO public.authors (id, name) VALUES (659, 'Ruth Westheimer');
INSERT INTO public.authors (id, name) VALUES (660, 'Jennifer Watson');
INSERT INTO public.authors (id, name) VALUES (661, 'David D. Burns');
INSERT INTO public.authors (id, name) VALUES (662, 'Elisabeth K??bler-Ross');
INSERT INTO public.authors (id, name) VALUES (663, 'Lynne Ann DeSpelder');
INSERT INTO public.authors (id, name) VALUES (664, 'Albert Lee Strickland');
INSERT INTO public.authors (id, name) VALUES (665, 'Mark Shepard');
INSERT INTO public.authors (id, name) VALUES (666, 'Stephen R. Covey');
INSERT INTO public.authors (id, name) VALUES (667, 'Dan Millman');
INSERT INTO public.authors (id, name) VALUES (668, 'Robert D. San Souci');
INSERT INTO public.authors (id, name) VALUES (669, 'T. Taylor Bruce');
INSERT INTO public.authors (id, name) VALUES (670, 'Lance Armstrong');
INSERT INTO public.authors (id, name) VALUES (671, 'Sally Jenkins');
INSERT INTO public.authors (id, name) VALUES (672, 'John Wilcockson');
INSERT INTO public.authors (id, name) VALUES (673, 'Graham   Watson');
INSERT INTO public.authors (id, name) VALUES (674, 'Truman Capote');
INSERT INTO public.authors (id, name) VALUES (675, 'Reynolds Price');
INSERT INTO public.authors (id, name) VALUES (676, 'Margaret Truman');
INSERT INTO public.authors (id, name) VALUES (677, 'Scott Brick');
INSERT INTO public.authors (id, name) VALUES (678, 'Steven Johnson');
INSERT INTO public.authors (id, name) VALUES (679, 'Temple Grandin');
INSERT INTO public.authors (id, name) VALUES (680, 'Margaret M. Scariano');
INSERT INTO public.authors (id, name) VALUES (681, 'Iris Fry');
INSERT INTO public.authors (id, name) VALUES (682, 'Edith Wharton');
INSERT INTO public.authors (id, name) VALUES (683, 'Laszlo Kubinyi');
INSERT INTO public.authors (id, name) VALUES (684, 'R.W.B. Lewis');
INSERT INTO public.authors (id, name) VALUES (685, 'Maureen Howard');
INSERT INTO public.authors (id, name) VALUES (686, 'Cynthia Griffin Wolff');
INSERT INTO public.authors (id, name) VALUES (687, 'Alton Raible');
INSERT INTO public.authors (id, name) VALUES (688, 'John Lloyd');
INSERT INTO public.authors (id, name) VALUES (689, 'Humphrey Carpenter');
INSERT INTO public.authors (id, name) VALUES (690, 'Christopher Tolkien');
INSERT INTO public.authors (id, name) VALUES (691, 'Ruth S. Noel');
INSERT INTO public.authors (id, name) VALUES (692, 'Christina Scull');
INSERT INTO public.authors (id, name) VALUES (693, 'Wayne G. Hammond');
INSERT INTO public.authors (id, name) VALUES (694, 'E.V. Gordon');
INSERT INTO public.authors (id, name) VALUES (695, 'A.R. Taylor');
INSERT INTO public.authors (id, name) VALUES (696, 'Sarah M.  Anderson');
INSERT INTO public.authors (id, name) VALUES (697, 'Karen Swenson');
INSERT INTO public.authors (id, name) VALUES (698, 'Jeffery Deaver');
INSERT INTO public.authors (id, name) VALUES (699, 'Paul Yee');
INSERT INTO public.authors (id, name) VALUES (700, 'Herman Melville');
INSERT INTO public.authors (id, name) VALUES (701, 'William Hootkins');
INSERT INTO public.authors (id, name) VALUES (702, 'Jan Needle');
INSERT INTO public.authors (id, name) VALUES (703, 'Patrick Benson');
INSERT INTO public.authors (id, name) VALUES (704, 'Carl F. Hovde');
INSERT INTO public.authors (id, name) VALUES (705, 'Geraldine McCaughrean');
INSERT INTO public.authors (id, name) VALUES (706, 'Victor G. Ambrus');
INSERT INTO public.authors (id, name) VALUES (707, 'Edward F. Edinger');
INSERT INTO public.authors (id, name) VALUES (708, 'Julian Markels');
INSERT INTO public.authors (id, name) VALUES (709, 'Elizabeth A. Schultz');
INSERT INTO public.authors (id, name) VALUES (710, 'Steve Martini');
INSERT INTO public.authors (id, name) VALUES (711, 'Mark Twain');
INSERT INTO public.authors (id, name) VALUES (712, 'Grover Gardner');
INSERT INTO public.authors (id, name) VALUES (713, 'Susan  Griffith');
INSERT INTO public.authors (id, name) VALUES (714, 'Theocritus');
INSERT INTO public.authors (id, name) VALUES (715, 'Hesiod');
INSERT INTO public.authors (id, name) VALUES (716, 'Glenn W. Most');
INSERT INTO public.authors (id, name) VALUES (717, 'Simon Gikandi');
INSERT INTO public.authors (id, name) VALUES (718, 'H.G. Wells');
INSERT INTO public.authors (id, name) VALUES (719, 'Patrick Parrinder');
INSERT INTO public.authors (id, name) VALUES (720, 'Steven McLean');
INSERT INTO public.authors (id, name) VALUES (721, 'Marina Warner');
INSERT INTO public.authors (id, name) VALUES (722, 'Benjamin Beard');
INSERT INTO public.authors (id, name) VALUES (723, 'Melvin Burgess');
INSERT INTO public.authors (id, name) VALUES (724, 'John R. Hammond');
INSERT INTO public.authors (id, name) VALUES (725, 'Ursula K. Le Guin');
INSERT INTO public.authors (id, name) VALUES (726, 'Edward Mendelson');
INSERT INTO public.authors (id, name) VALUES (727, 'Umberto Eco');
INSERT INTO public.authors (id, name) VALUES (728, 'Henri J.M. Nouwen');
INSERT INTO public.authors (id, name) VALUES (729, 'Timothy B. Tyson');
INSERT INTO public.authors (id, name) VALUES (730, 'Jos?© Saramago');
INSERT INTO public.authors (id, name) VALUES (731, 'Giovanni Pontiero');
INSERT INTO public.authors (id, name) VALUES (732, 'Peter S?­s');
INSERT INTO public.authors (id, name) VALUES (733, 'Pilar del R?­o');
INSERT INTO public.authors (id, name) VALUES (734, 'Jihad El');
INSERT INTO public.authors (id, name) VALUES (735, 'H.M. Nahmad');
INSERT INTO public.authors (id, name) VALUES (736, 'Robert Hillyer');
INSERT INTO public.authors (id, name) VALUES (737, 'Jack Kerouac');
INSERT INTO public.authors (id, name) VALUES (738, 'Ann Charters');
INSERT INTO public.authors (id, name) VALUES (739, 'Mark Stevens');
INSERT INTO public.authors (id, name) VALUES (740, 'Annalyn Swan');
INSERT INTO public.authors (id, name) VALUES (741, 'Julie Sylvester');
INSERT INTO public.authors (id, name) VALUES (742, 'David Sylvester');
INSERT INTO public.authors (id, name) VALUES (743, 'David  Allen');
INSERT INTO public.authors (id, name) VALUES (744, 'Tina Blythe');
INSERT INTO public.authors (id, name) VALUES (745, 'Gene Thompson-Grove');
INSERT INTO public.authors (id, name) VALUES (746, 'Sun Tzu');
INSERT INTO public.authors (id, name) VALUES (747, 'Mark McNeilly');
INSERT INTO public.authors (id, name) VALUES (748, 'Al Ries');
INSERT INTO public.authors (id, name) VALUES (749, 'Jack Trout');
INSERT INTO public.authors (id, name) VALUES (750, 'Seth Godin');
INSERT INTO public.authors (id, name) VALUES (751, 'Clayton M. Christensen');
INSERT INTO public.authors (id, name) VALUES (752, 'L.J. Ganser');
INSERT INTO public.authors (id, name) VALUES (753, 'David Trotter');
INSERT INTO public.authors (id, name) VALUES (754, 'Charlotte Mitchell');
INSERT INTO public.authors (id, name) VALUES (755, 'Edgar Rosenberg');
INSERT INTO public.authors (id, name) VALUES (756, 'Erasmus');
INSERT INTO public.authors (id, name) VALUES (757, 'Martin Luther');
INSERT INTO public.authors (id, name) VALUES (758, 'Philip S. Watson');
INSERT INTO public.authors (id, name) VALUES (759, 'E. Gordon Rupp');
INSERT INTO public.authors (id, name) VALUES (760, 'Harper Lee');
INSERT INTO public.authors (id, name) VALUES (761, 'Sissy Spacek');
INSERT INTO public.authors (id, name) VALUES (762, 'David H. Chilton');
INSERT INTO public.authors (id, name) VALUES (763, 'Jonathan Swift');
INSERT INTO public.authors (id, name) VALUES (764, 'Jesse Gale');
INSERT INTO public.authors (id, name) VALUES (765, 'Xavier de C.');
INSERT INTO public.authors (id, name) VALUES (766, 'Joseph Rowe');
INSERT INTO public.authors (id, name) VALUES (767, 'R.D. Gooder');
INSERT INTO public.authors (id, name) VALUES (768, 'Myra Jehlen');
INSERT INTO public.authors (id, name) VALUES (769, 'Leo Bersani');
INSERT INTO public.authors (id, name) VALUES (770, 'John Hollander');
INSERT INTO public.authors (id, name) VALUES (771, 'David Bromwich');
INSERT INTO public.authors (id, name) VALUES (772, 'Geoffrey Chaucer');
INSERT INTO public.authors (id, name) VALUES (773, 'Nevill Coghill');
INSERT INTO public.authors (id, name) VALUES (774, 'David  Wright');
INSERT INTO public.authors (id, name) VALUES (775, 'Jill Mann');
INSERT INTO public.authors (id, name) VALUES (776, 'Vincent Foster Hopper');
INSERT INTO public.authors (id, name) VALUES (777, 'Helen  Cooper');
INSERT INTO public.authors (id, name) VALUES (778, 'Brian Stone');
INSERT INTO public.authors (id, name) VALUES (779, 'Larry Dean Benson');
INSERT INTO public.authors (id, name) VALUES (780, 'F.N. Robinson');
INSERT INTO public.authors (id, name) VALUES (781, 'Theodore Morrison');
INSERT INTO public.authors (id, name) VALUES (782, 'Mark Kurlansky');
INSERT INTO public.authors (id, name) VALUES (783, 'Deloris Jordan');
INSERT INTO public.authors (id, name) VALUES (784, 'Kadir Nelson');
INSERT INTO public.authors (id, name) VALUES (785, 'Roslyn M. Jordan');
INSERT INTO public.authors (id, name) VALUES (786, 'Monique Truong');
INSERT INTO public.authors (id, name) VALUES (787, 'Abdul Rahman Munif');
INSERT INTO public.authors (id, name) VALUES (788, 'Peter Theroux');
INSERT INTO public.authors (id, name) VALUES (789, 'Kim Stanley Robinson');
INSERT INTO public.authors (id, name) VALUES (790, 'Walter Benjamin');
INSERT INTO public.authors (id, name) VALUES (791, 'Hannah Arendt');
INSERT INTO public.authors (id, name) VALUES (792, 'Harry Zohn');
INSERT INTO public.authors (id, name) VALUES (793, 'Leon Wieseltier');
INSERT INTO public.authors (id, name) VALUES (794, 'Saul Steinberg');
INSERT INTO public.authors (id, name) VALUES (795, 'Joel Smith');
INSERT INTO public.authors (id, name) VALUES (796, 'Charles Simic');
INSERT INTO public.authors (id, name) VALUES (797, 'Philip Dutre');
INSERT INTO public.authors (id, name) VALUES (798, 'David Guterson');
INSERT INTO public.authors (id, name) VALUES (799, 'Dave Pelzer');
INSERT INTO public.authors (id, name) VALUES (800, 'William S. Pollack');
INSERT INTO public.authors (id, name) VALUES (801, 'Mary Pipher');
INSERT INTO public.authors (id, name) VALUES (802, 'Douglas Coupland');
INSERT INTO public.authors (id, name) VALUES (803, 'Jean Aitchison');
INSERT INTO public.authors (id, name) VALUES (804, 'Diana M. Lewis');
INSERT INTO public.authors (id, name) VALUES (805, 'Ernest Becker');
INSERT INTO public.authors (id, name) VALUES (806, 'Sam Keen');
INSERT INTO public.authors (id, name) VALUES (807, 'Daniel Goleman');
INSERT INTO public.authors (id, name) VALUES (808, 'Howard Zinn');
INSERT INTO public.authors (id, name) VALUES (809, 'Kathy Emery');
INSERT INTO public.authors (id, name) VALUES (810, 'Ellen Gordon Reeves');
INSERT INTO public.authors (id, name) VALUES (811, 'Richard Hollis');
INSERT INTO public.authors (id, name) VALUES (812, 'Lisa Lowe');
INSERT INTO public.authors (id, name) VALUES (813, 'Jonathan Hale');
INSERT INTO public.authors (id, name) VALUES (814, 'David Bodanis');
INSERT INTO public.authors (id, name) VALUES (815, 'Rolland Hein');
INSERT INTO public.authors (id, name) VALUES (816, 'Clyde S. Kilby');
INSERT INTO public.authors (id, name) VALUES (817, 'Giotto di Bondone');
INSERT INTO public.authors (id, name) VALUES (818, 'Mary Chambers');
INSERT INTO public.authors (id, name) VALUES (819, 'Friedrich Nietzsche');
INSERT INTO public.authors (id, name) VALUES (820, 'Raymond Geuss');
INSERT INTO public.authors (id, name) VALUES (821, 'Ronald Speirs');
INSERT INTO public.authors (id, name) VALUES (822, 'Francis Golffing');
INSERT INTO public.authors (id, name) VALUES (823, 'Michael Tanner');
INSERT INTO public.authors (id, name) VALUES (824, 'Shaun Whiteside');
INSERT INTO public.authors (id, name) VALUES (825, 'Alastair Lamb');
INSERT INTO public.authors (id, name) VALUES (826, 'David Lionel Smith');
INSERT INTO public.authors (id, name) VALUES (827, 'Sherley Anne Williams');
INSERT INTO public.authors (id, name) VALUES (828, 'Katherine Paterson');
INSERT INTO public.authors (id, name) VALUES (829, 'Donna Diamond');
INSERT INTO public.authors (id, name) VALUES (830, 'Emil M. Cioran');
INSERT INTO public.authors (id, name) VALUES (831, 'Richard Howard');
INSERT INTO public.authors (id, name) VALUES (832, 'Tanya Huff');
INSERT INTO public.authors (id, name) VALUES (833, 'Tracy Chevalier');
INSERT INTO public.authors (id, name) VALUES (834, 'Rosalind Laker');
INSERT INTO public.authors (id, name) VALUES (835, 'Tom Hunter');
INSERT INTO public.authors (id, name) VALUES (836, 'Colin Wiggins');
INSERT INTO public.authors (id, name) VALUES (837, 'Tite Kubo');
INSERT INTO public.authors (id, name) VALUES (838, 'Tsugumi Ohba');
INSERT INTO public.authors (id, name) VALUES (839, 'Takeshi Obata');
INSERT INTO public.authors (id, name) VALUES (840, '?¤§? ´ ?¤???');
INSERT INTO public.authors (id, name) VALUES (841, '?°?ç ??');
INSERT INTO public.authors (id, name) VALUES (842, 'Valerie Parv');
INSERT INTO public.authors (id, name) VALUES (843, 'John E. Woods');
INSERT INTO public.authors (id, name) VALUES (844, 'Jean-Jacques Semp?©');
INSERT INTO public.authors (id, name) VALUES (845, 'Steve Chorney');
INSERT INTO public.authors (id, name) VALUES (846, 'Mike  Rowe');
INSERT INTO public.authors (id, name) VALUES (847, 'Ronald Radano');
INSERT INTO public.authors (id, name) VALUES (848, 'Daniel Defoe');
INSERT INTO public.authors (id, name) VALUES (849, 'Virginia Woolf');
INSERT INTO public.authors (id, name) VALUES (850, 'John J. Richetti');
INSERT INTO public.authors (id, name) VALUES (851, 'Michael Shinagel');
INSERT INTO public.authors (id, name) VALUES (852, 'Manuel Schonhorn');
INSERT INTO public.authors (id, name) VALUES (853, 'Charles   Johnson');
INSERT INTO public.authors (id, name) VALUES (854, 'Paul Baender');
INSERT INTO public.authors (id, name) VALUES (855, 'Dahlia Armon');
INSERT INTO public.authors (id, name) VALUES (856, 'Walter Blair');
INSERT INTO public.authors (id, name) VALUES (857, 'Lee Nelson');
INSERT INTO public.authors (id, name) VALUES (858, 'Guy Cardwell');
INSERT INTO public.authors (id, name) VALUES (859, 'John Seelye');
INSERT INTO public.authors (id, name) VALUES (860, 'Walter Trier');
INSERT INTO public.authors (id, name) VALUES (861, 'E.W. Kemble');
INSERT INTO public.authors (id, name) VALUES (862, 'George Saunders');
INSERT INTO public.authors (id, name) VALUES (863, 'Michael Patrick Hearn');
INSERT INTO public.authors (id, name) VALUES (864, 'Lin Salamo');
INSERT INTO public.authors (id, name) VALUES (865, 'Victor Fischer');
INSERT INTO public.authors (id, name) VALUES (866, 'Michael B. Frank');
INSERT INTO public.authors (id, name) VALUES (867, 'Charles Neider');
INSERT INTO public.authors (id, name) VALUES (868, 'Louis J. Budd');
INSERT INTO public.authors (id, name) VALUES (869, 'James Hilton');
INSERT INTO public.authors (id, name) VALUES (870, 'C. Michael Dudash');
INSERT INTO public.authors (id, name) VALUES (871, 'Stephen W. Hines');
INSERT INTO public.authors (id, name) VALUES (872, 'Nancy Friday');
INSERT INTO public.authors (id, name) VALUES (873, 'Frances Hodgson Burnett');
INSERT INTO public.authors (id, name) VALUES (874, 'Sandra M. Gilbert');
INSERT INTO public.authors (id, name) VALUES (875, 'Martha Hailey DuBose');
INSERT INTO public.authors (id, name) VALUES (876, 'Lucy Corvino');
INSERT INTO public.authors (id, name) VALUES (877, 'Arthur Pober');
INSERT INTO public.authors (id, name) VALUES (878, 'Alison Lurie');
INSERT INTO public.authors (id, name) VALUES (879, 'Nancy Bond');
INSERT INTO public.authors (id, name) VALUES (880, 'Ann Thwaite');
INSERT INTO public.authors (id, name) VALUES (881, 'Amy Cotler');
INSERT INTO public.authors (id, name) VALUES (882, 'Prudence See');
INSERT INTO public.authors (id, name) VALUES (883, 'Thomas Sowell');
INSERT INTO public.authors (id, name) VALUES (884, 'Selina Shirley Hastings');
INSERT INTO public.authors (id, name) VALUES (885, 'Juan Wijngaard');
INSERT INTO public.authors (id, name) VALUES (886, 'Alcoholics Anonymous');
INSERT INTO public.authors (id, name) VALUES (887, 'Overeaters Anonymous');
INSERT INTO public.authors (id, name) VALUES (888, 'Kimon Nicolaides');
INSERT INTO public.authors (id, name) VALUES (889, 'Mamie Harmon');
INSERT INTO public.authors (id, name) VALUES (890, 'Andrew Weil');
INSERT INTO public.authors (id, name) VALUES (891, 'Jonathan Safran Foer');
INSERT INTO public.authors (id, name) VALUES (892, 'Jonathan Rosen');
INSERT INTO public.authors (id, name) VALUES (893, 'Lawrence M. Lasher');
INSERT INTO public.authors (id, name) VALUES (894, 'Aleksandar Hemon');
INSERT INTO public.authors (id, name) VALUES (895, 'Matthew Barber');
INSERT INTO public.authors (id, name) VALUES (896, 'Elizabeth von Arnim');
INSERT INTO public.authors (id, name) VALUES (897, 'Benjamin DeMott');
INSERT INTO public.authors (id, name) VALUES (898, 'Lionel Trilling');
INSERT INTO public.authors (id, name) VALUES (899, 'Gilbert Adair');
INSERT INTO public.authors (id, name) VALUES (900, 'Elizabeth Heine');
INSERT INTO public.authors (id, name) VALUES (901, 'P.N. Furbank');
INSERT INTO public.authors (id, name) VALUES (902, 'Robert Hellenga');
INSERT INTO public.authors (id, name) VALUES (903, 'Gordon S. Wood');
INSERT INTO public.authors (id, name) VALUES (904, 'Gordon Korman');
INSERT INTO public.authors (id, name) VALUES (905, 'Deborah  Gordon');
INSERT INTO public.authors (id, name) VALUES (906, 'Ivo AndriÄ');
INSERT INTO public.authors (id, name) VALUES (907, 'William H. McNeill');
INSERT INTO public.authors (id, name) VALUES (908, 'Jean Estoril');
INSERT INTO public.authors (id, name) VALUES (909, 'Pascale Delpech');
INSERT INTO public.authors (id, name) VALUES (910, 'Mabel Esther Allan');
INSERT INTO public.authors (id, name) VALUES (911, 'Reginald E. Allen');
INSERT INTO public.authors (id, name) VALUES (912, 'Aristotle');
INSERT INTO public.authors (id, name) VALUES (913, 'W.S. Hett');
INSERT INTO public.authors (id, name) VALUES (914, 'Ian C. Storey');
INSERT INTO public.authors (id, name) VALUES (915, 'Gilbert Murray');
INSERT INTO public.authors (id, name) VALUES (916, 'Alan Brennert');
INSERT INTO public.authors (id, name) VALUES (917, 'Eric Jensen');
INSERT INTO public.authors (id, name) VALUES (918, 'Angus Gellatly');
INSERT INTO public.authors (id, name) VALUES (919, 'Oscar Z??rate');
INSERT INTO public.authors (id, name) VALUES (920, 'Richard Appignanesi');
INSERT INTO public.authors (id, name) VALUES (921, 'Isabel Allende');
INSERT INTO public.authors (id, name) VALUES (922, 'Margaret Sayers Peden');
INSERT INTO public.authors (id, name) VALUES (923, 'Richard D. Woods');
INSERT INTO public.authors (id, name) VALUES (924, 'Kenneth M. Taggart');
INSERT INTO public.authors (id, name) VALUES (925, 'Ernst E. Jonas');
INSERT INTO public.authors (id, name) VALUES (926, 'Jenny Sanders');
INSERT INTO public.authors (id, name) VALUES (927, 'S.D. Schindler');
INSERT INTO public.authors (id, name) VALUES (928, 'Dalai Lama XIV');
INSERT INTO public.authors (id, name) VALUES (929, 'Open City Magazine');
INSERT INTO public.authors (id, name) VALUES (930, 'James Purdy');
INSERT INTO public.authors (id, name) VALUES (931, 'Deborah Garrison');
INSERT INTO public.authors (id, name) VALUES (932, 'Rem Koolhaas');
INSERT INTO public.authors (id, name) VALUES (933, 'Rick Moody');
INSERT INTO public.authors (id, name) VALUES (934, 'Strawberry Saroyan');
INSERT INTO public.authors (id, name) VALUES (935, 'Debra Garrison');
INSERT INTO public.authors (id, name) VALUES (936, 'Wallace Stegner');
INSERT INTO public.authors (id, name) VALUES (937, 'Jackson J. Benson');
INSERT INTO public.authors (id, name) VALUES (938, 'Steve Krug');
INSERT INTO public.authors (id, name) VALUES (939, 'Louis de Berni?¨res');
INSERT INTO public.authors (id, name) VALUES (940, 'Fa??za Gu?¨ne');
INSERT INTO public.authors (id, name) VALUES (941, 'Sarah    Adams');
INSERT INTO public.authors (id, name) VALUES (942, 'Lawrence Otis Graham');
INSERT INTO public.authors (id, name) VALUES (943, 'Otis Williams');
INSERT INTO public.authors (id, name) VALUES (944, 'Patricia Romanowski');
INSERT INTO public.authors (id, name) VALUES (945, 'Colleen McCullough');
INSERT INTO public.authors (id, name) VALUES (946, 'Jill Colella');
INSERT INTO public.authors (id, name) VALUES (947, 'Mitch Albom');
INSERT INTO public.authors (id, name) VALUES (948, 'Tim O''Brien');
INSERT INTO public.authors (id, name) VALUES (949, 'Nicholas Sparks');
INSERT INTO public.authors (id, name) VALUES (950, 'Micah Sparks');
INSERT INTO public.authors (id, name) VALUES (951, 'Ram??n Gonz??lez F?©rriz');
INSERT INTO public.authors (id, name) VALUES (952, 'Gwyn Hyman Rubio');
INSERT INTO public.authors (id, name) VALUES (953, 'Marisha Pessl');
INSERT INTO public.authors (id, name) VALUES (954, 'Lois Beckwith');
INSERT INTO public.authors (id, name) VALUES (955, 'Baruch Spinoza');
INSERT INTO public.authors (id, name) VALUES (956, 'Janet Evanovich');
INSERT INTO public.authors (id, name) VALUES (957, 'Jayne Ann Krentz');
INSERT INTO public.authors (id, name) VALUES (958, 'Sarah Ban Breathnach');
INSERT INTO public.authors (id, name) VALUES (959, 'Marjorie Weinman Sharmat');
INSERT INTO public.authors (id, name) VALUES (960, 'Mitchell Sharmat');
INSERT INTO public.authors (id, name) VALUES (961, 'George E. Stanley');
INSERT INTO public.authors (id, name) VALUES (962, 'Kaho Miyasaka');
INSERT INTO public.authors (id, name) VALUES (963, 'Fulton J. Sheen');
INSERT INTO public.authors (id, name) VALUES (964, 'George MacDonald');
INSERT INTO public.authors (id, name) VALUES (965, 'Michael R. Phillips');
INSERT INTO public.authors (id, name) VALUES (966, 'Ivan Turgenev');
INSERT INTO public.authors (id, name) VALUES (967, 'Jane Moore');
INSERT INTO public.authors (id, name) VALUES (968, 'Amanda Clark');
INSERT INTO public.authors (id, name) VALUES (969, 'Justin   O''Brien');
INSERT INTO public.authors (id, name) VALUES (970, 'Antonio Gramsci');
INSERT INTO public.authors (id, name) VALUES (971, 'L.M. Montgomery');
INSERT INTO public.authors (id, name) VALUES (972, 'Mary Henley Rubio');
INSERT INTO public.authors (id, name) VALUES (973, 'Elizabeth Hillman Waterston');
INSERT INTO public.authors (id, name) VALUES (974, 'Rea Wilmshurst');
INSERT INTO public.authors (id, name) VALUES (975, 'Susan O''Malley');
INSERT INTO public.authors (id, name) VALUES (976, 'Arthur Conan Doyle');
INSERT INTO public.authors (id, name) VALUES (977, 'Leslie S. Klinger');
INSERT INTO public.authors (id, name) VALUES (978, 'E.J. Wagner');
INSERT INTO public.authors (id, name) VALUES (979, 'John Gielgud');
INSERT INTO public.authors (id, name) VALUES (980, 'Ralph Richardson');
INSERT INTO public.authors (id, name) VALUES (981, 'Orson Welles');
INSERT INTO public.authors (id, name) VALUES (982, 'Nick Rennison');
INSERT INTO public.authors (id, name) VALUES (983, 'NOT A BOOK');
INSERT INTO public.authors (id, name) VALUES (984, 'Paul Bachem');
INSERT INTO public.authors (id, name) VALUES (985, 'Eric Tyson');
INSERT INTO public.authors (id, name) VALUES (986, 'Rich Tennant');
INSERT INTO public.authors (id, name) VALUES (987, 'Clare Naylor');
INSERT INTO public.authors (id, name) VALUES (988, 'Bruce H. Wilkinson');
INSERT INTO public.authors (id, name) VALUES (989, 'David Kopp');
INSERT INTO public.authors (id, name) VALUES (990, 'Heather Harpham Kopp');
INSERT INTO public.authors (id, name) VALUES (991, 'Lois Lowry');
INSERT INTO public.authors (id, name) VALUES (992, 'Bill Brittain');
INSERT INTO public.authors (id, name) VALUES (993, 'Andrew Glass');
INSERT INTO public.authors (id, name) VALUES (994, 'Jack Weatherford');
INSERT INTO public.authors (id, name) VALUES (995, 'Claire Messud');
INSERT INTO public.authors (id, name) VALUES (996, 'Zadie Smith');
INSERT INTO public.authors (id, name) VALUES (997, 'Libba Bray');
INSERT INTO public.authors (id, name) VALUES (998, 'Kym Douglas');
INSERT INTO public.authors (id, name) VALUES (999, 'Cindy Pearlman');
INSERT INTO public.authors (id, name) VALUES (1000, 'Ann Patchett');
INSERT INTO public.authors (id, name) VALUES (1001, 'Graham Greene');
INSERT INTO public.authors (id, name) VALUES (1002, 'Pico Iyer');
INSERT INTO public.authors (id, name) VALUES (1003, 'John Updike');
INSERT INTO public.authors (id, name) VALUES (1004, 'Christopher Hitchens');
INSERT INTO public.authors (id, name) VALUES (1005, 'Paul Theroux');
INSERT INTO public.authors (id, name) VALUES (1006, 'Robert  Stone');
INSERT INTO public.authors (id, name) VALUES (1007, 'Chuck Palahniuk');
INSERT INTO public.authors (id, name) VALUES (1008, 'Warner Berthoff');
INSERT INTO public.authors (id, name) VALUES (1009, 'Robert Penn Warren');
INSERT INTO public.authors (id, name) VALUES (1010, 'G. Thomas Tanselle');
INSERT INTO public.authors (id, name) VALUES (1011, 'Harrison Hayford');
INSERT INTO public.authors (id, name) VALUES (1012, 'Harold Beaver');
INSERT INTO public.authors (id, name) VALUES (1013, 'Helen Ericson');
INSERT INTO public.authors (id, name) VALUES (1014, 'Maya Gold');
INSERT INTO public.authors (id, name) VALUES (1015, 'Ian Fleming');
INSERT INTO public.authors (id, name) VALUES (1016, 'Madeleine Brent');
INSERT INTO public.authors (id, name) VALUES (1017, 'George Condo');
INSERT INTO public.authors (id, name) VALUES (1018, 'Noel Streatfeild');
INSERT INTO public.authors (id, name) VALUES (1019, 'Diane Goode');
INSERT INTO public.authors (id, name) VALUES (1020, 'Rumer Godden');
INSERT INTO public.authors (id, name) VALUES (1021, 'Gary Blythe');
INSERT INTO public.authors (id, name) VALUES (1022, 'Christian Birmingham');
INSERT INTO public.authors (id, name) VALUES (1023, 'Anne Chisholm');
INSERT INTO public.authors (id, name) VALUES (1024, 'Jonathan Franzen');
INSERT INTO public.authors (id, name) VALUES (1025, 'Lisa Whelchel');
INSERT INTO public.authors (id, name) VALUES (1026, 'Stormie Omartian');
INSERT INTO public.authors (id, name) VALUES (1027, 'Henri Blocher');
INSERT INTO public.authors (id, name) VALUES (1028, 'Nina Bangs');
INSERT INTO public.authors (id, name) VALUES (1029, 'Michael Jan Friedman');
INSERT INTO public.authors (id, name) VALUES (1030, 'P.D. James');
INSERT INTO public.authors (id, name) VALUES (1031, 'Christa Seibicke');
INSERT INTO public.authors (id, name) VALUES (1032, 'Miguel de Cervantes Saavedra');
INSERT INTO public.authors (id, name) VALUES (1033, 'John Rutherford');
INSERT INTO public.authors (id, name) VALUES (1034, 'Roberto Gonz??lez Echevarr?­a');
INSERT INTO public.authors (id, name) VALUES (1035, 'Walter Starkie');
INSERT INTO public.authors (id, name) VALUES (1036, 'Tobias Smollett');
INSERT INTO public.authors (id, name) VALUES (1037, 'Carlos Fuentes');
INSERT INTO public.authors (id, name) VALUES (1038, 'Vladimir Nabokov');
INSERT INTO public.authors (id, name) VALUES (1039, 'Fredson Bowers');
INSERT INTO public.authors (id, name) VALUES (1040, 'Guy Davenport');
INSERT INTO public.authors (id, name) VALUES (1041, 'Samuel Putnam');
INSERT INTO public.authors (id, name) VALUES (1042, 'J.A. Jance');
INSERT INTO public.authors (id, name) VALUES (1043, 'Fern Michaels');
INSERT INTO public.authors (id, name) VALUES (1044, 'Eric Klinenberg');
INSERT INTO public.authors (id, name) VALUES (1045, 'Ruth Prawer Jhabvala');
INSERT INTO public.authors (id, name) VALUES (1046, 'Sarah Macdonald');
INSERT INTO public.authors (id, name) VALUES (1047, 'Joel Salatin');
INSERT INTO public.authors (id, name) VALUES (1048, 'Michael Pollan');
INSERT INTO public.authors (id, name) VALUES (1049, 'Nicole Krauss');
INSERT INTO public.authors (id, name) VALUES (1050, 'Thomas E. Woods Jr.');
INSERT INTO public.authors (id, name) VALUES (1051, 'Tom Standage');
INSERT INTO public.authors (id, name) VALUES (1052, 'Karen Armstrong');
INSERT INTO public.authors (id, name) VALUES (1053, 'William Hurt');
INSERT INTO public.authors (id, name) VALUES (1054, 'Barbara Fairchild');
INSERT INTO public.authors (id, name) VALUES (1055, 'Ina Garten');
INSERT INTO public.authors (id, name) VALUES (1056, 'Melanie Acevedo');
INSERT INTO public.authors (id, name) VALUES (1057, 'Diane Johnson');
INSERT INTO public.authors (id, name) VALUES (1058, 'Leonard Michaels');
INSERT INTO public.authors (id, name) VALUES (1059, 'Carlos Milla Soler');
INSERT INTO public.authors (id, name) VALUES (1060, 'Roberto Fernandez Sastre');
INSERT INTO public.authors (id, name) VALUES (1061, 'Laura Dave');
INSERT INTO public.authors (id, name) VALUES (1062, 'Dan Simmons');
INSERT INTO public.authors (id, name) VALUES (1063, 'Carlos Alberto Gardini');
INSERT INTO public.authors (id, name) VALUES (1064, 'J. Michael Straczynski');
INSERT INTO public.authors (id, name) VALUES (1065, 'Dan Jurgens');
INSERT INTO public.authors (id, name) VALUES (1066, 'Joachim K?¶rber');
INSERT INTO public.authors (id, name) VALUES (1067, 'Michael Chabon');
INSERT INTO public.authors (id, name) VALUES (1068, 'Glen David Gold');
INSERT INTO public.authors (id, name) VALUES (1069, 'Bill Sienkiewicz');
INSERT INTO public.authors (id, name) VALUES (1070, 'Howard Chaykin');
INSERT INTO public.authors (id, name) VALUES (1071, 'Gene Colan');
INSERT INTO public.authors (id, name) VALUES (1072, 'Steve Lieber');
INSERT INTO public.authors (id, name) VALUES (1073, 'Eric Wight');
INSERT INTO public.authors (id, name) VALUES (1074, 'Kevin  McCarthy');
INSERT INTO public.authors (id, name) VALUES (1075, 'Max Lucado');
INSERT INTO public.authors (id, name) VALUES (1076, 'Nick Caistor');
INSERT INTO public.authors (id, name) VALUES (1077, 'J.D. Salinger');
INSERT INTO public.authors (id, name) VALUES (1078, 'Brenda Walpole');
INSERT INTO public.authors (id, name) VALUES (1079, 'Bret Easton Ellis');
INSERT INTO public.authors (id, name) VALUES (1080, 'Scott Turow');
INSERT INTO public.authors (id, name) VALUES (1081, 'Pete Hautman');
INSERT INTO public.authors (id, name) VALUES (1082, 'Ronald B. Flowers');
INSERT INTO public.authors (id, name) VALUES (1083, 'Thomas  Moore');
INSERT INTO public.authors (id, name) VALUES (1084, 'Arielle Ford');
INSERT INTO public.authors (id, name) VALUES (1085, 'Deepak Chopra');
INSERT INTO public.authors (id, name) VALUES (1086, 'Viktor E. Frankl');
INSERT INTO public.authors (id, name) VALUES (1087, 'Harold S. Kushner');
INSERT INTO public.authors (id, name) VALUES (1088, 'William J. Winslade');
INSERT INTO public.authors (id, name) VALUES (1089, 'Isle Lasch');
INSERT INTO public.authors (id, name) VALUES (1090, 'Gordon W. Allport');
INSERT INTO public.authors (id, name) VALUES (1091, 'Ilse Lasch');
INSERT INTO public.authors (id, name) VALUES (1092, 'Eric R. Kandel');
INSERT INTO public.authors (id, name) VALUES (1093, 'Peter Kent');
INSERT INTO public.authors (id, name) VALUES (1094, 'Johanna Rothman');
INSERT INTO public.authors (id, name) VALUES (1095, 'Esther Derby');
INSERT INTO public.authors (id, name) VALUES (1096, 'Brigid Avison');
INSERT INTO public.authors (id, name) VALUES (1097, 'Roderick Townley');
INSERT INTO public.authors (id, name) VALUES (1098, 'Ray Oldenburg');
INSERT INTO public.authors (id, name) VALUES (1099, 'James C. Collins');
INSERT INTO public.authors (id, name) VALUES (1100, 'Jerry I. Porras');
INSERT INTO public.authors (id, name) VALUES (1101, 'Amy Sedaris');
INSERT INTO public.authors (id, name) VALUES (1102, 'David Sedaris');
INSERT INTO public.authors (id, name) VALUES (1103, 'Richard Yates');
INSERT INTO public.authors (id, name) VALUES (1104, 'Dorothy Parker');
INSERT INTO public.authors (id, name) VALUES (1105, 'Joyce Carol Oates');
INSERT INTO public.authors (id, name) VALUES (1106, 'Lorrie Moore');
INSERT INTO public.authors (id, name) VALUES (1107, 'Flannery O''Connor');
INSERT INTO public.authors (id, name) VALUES (1108, 'Amy Hempel');
INSERT INTO public.authors (id, name) VALUES (1109, 'Akhil   Sharma');
INSERT INTO public.authors (id, name) VALUES (1110, 'Tim Johnston');
INSERT INTO public.authors (id, name) VALUES (1111, 'Tobias Wolff');
INSERT INTO public.authors (id, name) VALUES (1112, 'Sarah Vowell');
INSERT INTO public.authors (id, name) VALUES (1113, 'Charles Baxter');
INSERT INTO public.authors (id, name) VALUES (1114, 'Jhumpa Lahiri');
INSERT INTO public.authors (id, name) VALUES (1115, 'Katherine Mansfield');
INSERT INTO public.authors (id, name) VALUES (1116, 'Alice Munro');
INSERT INTO public.authors (id, name) VALUES (1117, 'Jean Thompson');
INSERT INTO public.authors (id, name) VALUES (1118, 'Frank Gannon');
INSERT INTO public.authors (id, name) VALUES (1119, 'Patricia Highsmith');
INSERT INTO public.authors (id, name) VALUES (1120, 'Jincy Willett');
INSERT INTO public.authors (id, name) VALUES (1121, 'Ben Mezrich');
INSERT INTO public.authors (id, name) VALUES (1122, 'Pat Williams');
INSERT INTO public.authors (id, name) VALUES (1123, 'Peggy Matthews Rose');
INSERT INTO public.authors (id, name) VALUES (1124, 'Efrem Smith');
INSERT INTO public.authors (id, name) VALUES (1125, 'Phil   Jackson');
INSERT INTO public.authors (id, name) VALUES (1126, 'Tom Stanton');
INSERT INTO public.authors (id, name) VALUES (1127, 'James Ellroy');
INSERT INTO public.authors (id, name) VALUES (1128, 'Hans Blumenberg');
INSERT INTO public.authors (id, name) VALUES (1129, 'Greg  Taylor');
INSERT INTO public.authors (id, name) VALUES (1130, 'Larry Burkett');
INSERT INTO public.authors (id, name) VALUES (1131, 'Paul Michael');
INSERT INTO public.authors (id, name) VALUES (1132, 'Juanjo Estrella');
INSERT INTO public.authors (id, name) VALUES (1133, 'Bart D. Ehrman');
INSERT INTO public.authors (id, name) VALUES (1134, 'Nick Hornby');
INSERT INTO public.authors (id, name) VALUES (1135, 'Jess Walter');
INSERT INTO public.authors (id, name) VALUES (1136, 'Jennie Erdal');
INSERT INTO public.authors (id, name) VALUES (1137, 'Joshua Ferris');
INSERT INTO public.authors (id, name) VALUES (1138, 'D.J. Taylor');
INSERT INTO public.authors (id, name) VALUES (1139, 'Huw Richards');
INSERT INTO public.authors (id, name) VALUES (1140, 'Chris Pierson');
INSERT INTO public.authors (id, name) VALUES (1141, 'Roddy Doyle');
INSERT INTO public.authors (id, name) VALUES (1142, 'Harry Ritchie');
INSERT INTO public.authors (id, name) VALUES (1143, 'Harry Pearson');
INSERT INTO public.authors (id, name) VALUES (1144, 'Olly Wicken');
INSERT INTO public.authors (id, name) VALUES (1145, 'Graham Brack');
INSERT INTO public.authors (id, name) VALUES (1146, 'Matt Nation');
INSERT INTO public.authors (id, name) VALUES (1147, 'Ed Horton');
INSERT INTO public.authors (id, name) VALUES (1148, 'Don  Watson');
INSERT INTO public.authors (id, name) VALUES (1149, 'Ruth Downie');
INSERT INTO public.authors (id, name) VALUES (1150, 'Middlesex Borough Heritage Committee');
INSERT INTO public.authors (id, name) VALUES (1151, 'Stephen J. Burn');
INSERT INTO public.authors (id, name) VALUES (1152, 'Anthony Kiedis');
INSERT INTO public.authors (id, name) VALUES (1153, '?ric-Emmanuel Schmitt');
INSERT INTO public.authors (id, name) VALUES (1154, 'Sonallah Ibrahim');
INSERT INTO public.authors (id, name) VALUES (1155, '?µ??? ?§??? ???¨?±?§???');
INSERT INTO public.authors (id, name) VALUES (1156, 'Anthony Calderbank');
INSERT INTO public.authors (id, name) VALUES (1157, 'Sarah Dessen');
INSERT INTO public.authors (id, name) VALUES (1158, 'Dale Brown');
INSERT INTO public.authors (id, name) VALUES (1159, 'Jim DeFelice');
INSERT INTO public.authors (id, name) VALUES (1160, 'Chris  Williams');
INSERT INTO public.authors (id, name) VALUES (1161, 'Sandy Petersen');
INSERT INTO public.authors (id, name) VALUES (1162, 'Aidan Hartley');
INSERT INTO public.authors (id, name) VALUES (1163, 'Anderson Cooper');
INSERT INTO public.authors (id, name) VALUES (1164, 'Bentley Little');
INSERT INTO public.authors (id, name) VALUES (1165, 'Robert D. Siegel');
INSERT INTO public.authors (id, name) VALUES (1166, 'Todd Hanson');
INSERT INTO public.authors (id, name) VALUES (1167, 'Carol Kolb');
INSERT INTO public.authors (id, name) VALUES (1168, 'The Onion');
INSERT INTO public.authors (id, name) VALUES (1169, 'Ian Whybrow');
INSERT INTO public.authors (id, name) VALUES (1170, 'Deborah Allwright');
INSERT INTO public.authors (id, name) VALUES (1171, 'Joanne Rocklin');
INSERT INTO public.authors (id, name) VALUES (1172, 'Meredith Johnson');
INSERT INTO public.authors (id, name) VALUES (1173, 'Anthony Loyd');
INSERT INTO public.authors (id, name) VALUES (1174, 'Anthony Shadid');
INSERT INTO public.authors (id, name) VALUES (1175, 'Suketu Mehta');
INSERT INTO public.authors (id, name) VALUES (1176, 'Andrew X. Pham');
INSERT INTO public.authors (id, name) VALUES (1177, 'Chanrithy Him');
INSERT INTO public.authors (id, name) VALUES (1178, 'Loung Ung');
INSERT INTO public.authors (id, name) VALUES (1179, 'Ray Bradbury');
INSERT INTO public.authors (id, name) VALUES (1180, 'Christopher Hurt');
INSERT INTO public.authors (id, name) VALUES (1181, 'Gregory Rabassa');
INSERT INTO public.authors (id, name) VALUES (1182, 'J.S. Bernstein');
INSERT INTO public.authors (id, name) VALUES (1183, 'Robert DeMott');
INSERT INTO public.authors (id, name) VALUES (1184, 'Mick Wiggins');
INSERT INTO public.authors (id, name) VALUES (1185, 'Kelly McGrath Vlcek');
INSERT INTO public.authors (id, name) VALUES (1186, 'Neil Gaiman');
INSERT INTO public.authors (id, name) VALUES (1187, 'Jon Meacham');
INSERT INTO public.authors (id, name) VALUES (1188, 'Stephen Oppenheimer');
INSERT INTO public.authors (id, name) VALUES (1189, 'Yona Zeldis McDonough');
INSERT INTO public.authors (id, name) VALUES (1190, 'Nancy Harrison');
INSERT INTO public.authors (id, name) VALUES (1191, 'Jill Weber');
INSERT INTO public.authors (id, name) VALUES (1192, 'Harrison Edward Livingstone');
INSERT INTO public.authors (id, name) VALUES (1193, 'Robert Dallek');
INSERT INTO public.authors (id, name) VALUES (1194, 'Augusten Burroughs');
INSERT INTO public.authors (id, name) VALUES (1195, 'M. Scott Peck');
INSERT INTO public.authors (id, name) VALUES (1196, 'John Irving');
INSERT INTO public.authors (id, name) VALUES (1197, 'Atul Gawande');
INSERT INTO public.authors (id, name) VALUES (1198, 'Susanne Kuhlmann-Krieg');
INSERT INTO public.authors (id, name) VALUES (1199, 'Judith Viorst');
INSERT INTO public.authors (id, name) VALUES (1200, 'Richard  Hull');
INSERT INTO public.authors (id, name) VALUES (1201, 'Helen Fielding');
INSERT INTO public.authors (id, name) VALUES (1202, 'Carlos Ruiz Zaf??n');
INSERT INTO public.authors (id, name) VALUES (1203, 'Ruby K. Payne');
INSERT INTO public.authors (id, name) VALUES (1204, 'Lucia Graves');
INSERT INTO public.authors (id, name) VALUES (1205, 'David A. Black');
INSERT INTO public.authors (id, name) VALUES (1206, 'E.L. Konigsburg');
INSERT INTO public.authors (id, name) VALUES (1207, 'Sylvia Engdahl');
INSERT INTO public.authors (id, name) VALUES (1208, 'Matt Ridley');
INSERT INTO public.authors (id, name) VALUES (1209, 'David W. Mount');
INSERT INTO public.authors (id, name) VALUES (1210, 'James Shreeve');
INSERT INTO public.authors (id, name) VALUES (1211, 'Sandra Boynton');
INSERT INTO public.authors (id, name) VALUES (1212, 'Doreen Cronin');
INSERT INTO public.authors (id, name) VALUES (1213, 'Betsy Lewin');
INSERT INTO public.authors (id, name) VALUES (1214, 'Lisa Wheeler');
INSERT INTO public.authors (id, name) VALUES (1215, 'Ponder Goembel');
INSERT INTO public.authors (id, name) VALUES (1216, 'Charles A. Peek');
INSERT INTO public.authors (id, name) VALUES (1217, 'Joseph Heller');
INSERT INTO public.authors (id, name) VALUES (1218, 'Liza Dalby');
INSERT INTO public.authors (id, name) VALUES (1219, 'New Scientist');
INSERT INTO public.authors (id, name) VALUES (1220, 'Mick O''Hare');
INSERT INTO public.authors (id, name) VALUES (1221, 'Curt Meyer-Clason');
INSERT INTO public.authors (id, name) VALUES (1222, 'John Hemingway');
INSERT INTO public.authors (id, name) VALUES (1223, 'Patrick Hemingway');
INSERT INTO public.authors (id, name) VALUES (1224, 'Gregory H. Hemingway');
INSERT INTO public.authors (id, name) VALUES (1225, 'Charles Scribner Jr.');
INSERT INTO public.authors (id, name) VALUES (1226, 'Mark Bailey');
INSERT INTO public.authors (id, name) VALUES (1227, 'Edward Hemingway');
INSERT INTO public.authors (id, name) VALUES (1228, 'Sven Regener');
INSERT INTO public.authors (id, name) VALUES (1229, 'John Brownjohn');
INSERT INTO public.authors (id, name) VALUES (1230, 'Carlene Fredericka Brennen');
INSERT INTO public.authors (id, name) VALUES (1231, 'Hilary Hemingway');
INSERT INTO public.authors (id, name) VALUES (1232, 'Charlton Heston');
INSERT INTO public.authors (id, name) VALUES (1233, 'F. Scott Fitzgerald');
INSERT INTO public.authors (id, name) VALUES (1234, 'Matthew J. Bruccoli');
INSERT INTO public.authors (id, name) VALUES (1235, 'Judith S. Baughman');
INSERT INTO public.authors (id, name) VALUES (1236, 'Dave Page');
INSERT INTO public.authors (id, name) VALUES (1237, 'Patricia Hampl');
INSERT INTO public.authors (id, name) VALUES (1238, 'Arnold Goldman');
INSERT INTO public.authors (id, name) VALUES (1239, 'Richard Godden');
INSERT INTO public.authors (id, name) VALUES (1240, 'Kathleen Parkinson');
INSERT INTO public.authors (id, name) VALUES (1241, 'Tim Robbins');
INSERT INTO public.authors (id, name) VALUES (1242, 'Alexander Scourby');
INSERT INTO public.authors (id, name) VALUES (1243, 'Kate Maurer');
INSERT INTO public.authors (id, name) VALUES (1244, 'Noah Gordon');
INSERT INTO public.authors (id, name) VALUES (1245, 'Mirjana CvekiÄ');
INSERT INTO public.authors (id, name) VALUES (1246, 'Ljiljana CvekiÄ');
INSERT INTO public.authors (id, name) VALUES (1247, 'Noah Eli Gordon');
INSERT INTO public.authors (id, name) VALUES (1248, 'Elsa Mateo');
INSERT INTO public.authors (id, name) VALUES (1249, 'Peter   Sutton');
INSERT INTO public.authors (id, name) VALUES (1250, 'Paula S. Fass');
INSERT INTO public.authors (id, name) VALUES (1251, 'Steven L. Layne');
INSERT INTO public.authors (id, name) VALUES (1252, 'James L.W. West III');
INSERT INTO public.authors (id, name) VALUES (1253, 'Samuel B. Griffith');
INSERT INTO public.authors (id, name) VALUES (1254, 'Scott   Cunningham');
INSERT INTO public.authors (id, name) VALUES (1255, 'Peter Kuper');
INSERT INTO public.authors (id, name) VALUES (1256, 'Seth Tobocman');
INSERT INTO public.authors (id, name) VALUES (1257, 'Sabrina Jones');
INSERT INTO public.authors (id, name) VALUES (1258, 'Time-Life Books');
INSERT INTO public.authors (id, name) VALUES (1259, 'George Lucas');
INSERT INTO public.authors (id, name) VALUES (1260, 'Robert L. O''Connell');
INSERT INTO public.authors (id, name) VALUES (1261, 'John    Batchelor');
INSERT INTO public.authors (id, name) VALUES (1262, 'Susan Shillinglaw');
INSERT INTO public.authors (id, name) VALUES (1263, 'Elaine Steinbeck');
INSERT INTO public.authors (id, name) VALUES (1264, 'Richard Astro');
INSERT INTO public.authors (id, name) VALUES (1265, 'Dava Sobel');
INSERT INTO public.authors (id, name) VALUES (1266, 'William J.H. Andrewes');
INSERT INTO public.authors (id, name) VALUES (1267, 'William J. H. Andrewes');
INSERT INTO public.authors (id, name) VALUES (1268, 'Neil Armstrong');
INSERT INTO public.authors (id, name) VALUES (1269, 'Rebecca Aberg');
INSERT INTO public.authors (id, name) VALUES (1270, 'Jeanne Clidas');
INSERT INTO public.authors (id, name) VALUES (1271, 'William Andrewes');
INSERT INTO public.authors (id, name) VALUES (1272, 'Gavin Menzies');
INSERT INTO public.authors (id, name) VALUES (1273, 'Kristi Gold');
INSERT INTO public.authors (id, name) VALUES (1274, 'Nathaniel Philbrick');
INSERT INTO public.authors (id, name) VALUES (1275, 'Lerone Bennett Jr.');
INSERT INTO public.authors (id, name) VALUES (1276, 'Salman Rushdie');
INSERT INTO public.authors (id, name) VALUES (1277, 'Paul Birkbeck');
INSERT INTO public.authors (id, name) VALUES (1278, 'Steve McConnell');
INSERT INTO public.authors (id, name) VALUES (1279, 'Dale Carnegie');
INSERT INTO public.authors (id, name) VALUES (1280, 'Dorothy Carnegie');
INSERT INTO public.authors (id, name) VALUES (1281, 'Stuart R. Levine');
INSERT INTO public.authors (id, name) VALUES (1282, 'Michael A. Crom');
INSERT INTO public.authors (id, name) VALUES (1283, 'Alice   Miller');
INSERT INTO public.authors (id, name) VALUES (1284, 'Ruth Ward');
INSERT INTO public.authors (id, name) VALUES (1285, 'Spencer Johnson');
INSERT INTO public.authors (id, name) VALUES (1286, 'Kenneth H. Blanchard');
INSERT INTO public.authors (id, name) VALUES (1287, 'W. Chan Kim');
INSERT INTO public.authors (id, name) VALUES (1288, 'Ren?©e Mauborgne');
INSERT INTO public.authors (id, name) VALUES (1289, 'Joseph Conrad');
INSERT INTO public.authors (id, name) VALUES (1290, 'Cedric Watts');
INSERT INTO public.authors (id, name) VALUES (1291, 'Frank McCourt');
INSERT INTO public.authors (id, name) VALUES (1292, 'Jerome K. Jerome');
INSERT INTO public.authors (id, name) VALUES (1293, 'Jeremy Lewis');
INSERT INTO public.authors (id, name) VALUES (1294, 'Haruki Murakami');
INSERT INTO public.authors (id, name) VALUES (1295, 'Philip Gabriel');
INSERT INTO public.authors (id, name) VALUES (1296, 'Fyodor Dostoyevsky');
INSERT INTO public.authors (id, name) VALUES (1297, 'Manuel Komroff');
INSERT INTO public.authors (id, name) VALUES (1298, 'Fyodor Dostoevsky');
INSERT INTO public.authors (id, name) VALUES (1299, 'David McDuff');
INSERT INTO public.authors (id, name) VALUES (1300, 'Simon Vance');
INSERT INTO public.authors (id, name) VALUES (1301, 'Thomas R. Beyer Jr.');
INSERT INTO public.authors (id, name) VALUES (1302, 'Maire Jaanus');
INSERT INTO public.authors (id, name) VALUES (1303, 'James Lamar Roberts');
INSERT INTO public.authors (id, name) VALUES (1304, 'Peter Menzel');
INSERT INTO public.authors (id, name) VALUES (1305, 'Faith D''Aluisio');
INSERT INTO public.authors (id, name) VALUES (1306, 'Eric Carle');
INSERT INTO public.authors (id, name) VALUES (1307, 'Don    Wood');
INSERT INTO public.authors (id, name) VALUES (1308, 'Elinor J. Pinczes');
INSERT INTO public.authors (id, name) VALUES (1309, 'Bonnie Mackain');
INSERT INTO public.authors (id, name) VALUES (1310, 'Amitav Ghosh');
INSERT INTO public.authors (id, name) VALUES (1311, 'Geneen Roth');
INSERT INTO public.authors (id, name) VALUES (1312, 'Dave Eggers');
INSERT INTO public.authors (id, name) VALUES (1313, 'Lisa McCourt');
INSERT INTO public.authors (id, name) VALUES (1314, 'Cyd Moore');
INSERT INTO public.authors (id, name) VALUES (1315, 'Geraldine Brooks');
INSERT INTO public.authors (id, name) VALUES (1316, 'Tanya Remer Altmann');
INSERT INTO public.authors (id, name) VALUES (1317, 'American Academy of Pediatrics');
INSERT INTO public.authors (id, name) VALUES (1318, 'Stephen King');
INSERT INTO public.authors (id, name) VALUES (1319, 'Bernie Wrightson');
INSERT INTO public.authors (id, name) VALUES (1320, 'Kurt Vonnegut Jr.');
INSERT INTO public.authors (id, name) VALUES (1321, 'Daniel Simon');
INSERT INTO public.authors (id, name) VALUES (1322, 'Terry Southern');
INSERT INTO public.authors (id, name) VALUES (1323, 'David H. Goldsmith');
INSERT INTO public.authors (id, name) VALUES (1324, 'James Lundquist');
INSERT INTO public.authors (id, name) VALUES (1325, 'Lawrence R. Broer');
INSERT INTO public.authors (id, name) VALUES (1326, 'Peter J. Reed');
INSERT INTO public.authors (id, name) VALUES (1327, 'Loree Rackstraw');
INSERT INTO public.authors (id, name) VALUES (1328, 'William S. Doxey');
INSERT INTO public.authors (id, name) VALUES (1329, 'Jerome Klinkowitz');
INSERT INTO public.authors (id, name) VALUES (1330, 'Richard Giannone');
INSERT INTO public.authors (id, name) VALUES (1331, 'John L. Simons');
INSERT INTO public.authors (id, name) VALUES (1332, 'Leonard Mustazza');
INSERT INTO public.authors (id, name) VALUES (1333, 'Zoltan Ab di-Nagy');
INSERT INTO public.authors (id, name) VALUES (1334, 'Peter Freese');
INSERT INTO public.authors (id, name) VALUES (1335, 'Wendy B. Faris');
INSERT INTO public.authors (id, name) VALUES (1336, 'Anita Diamant');
INSERT INTO public.authors (id, name) VALUES (1337, 'Sandra Hack Polaski');
INSERT INTO public.authors (id, name) VALUES (1338, 'Ann Finding');
INSERT INTO public.authors (id, name) VALUES (1339, 'Marie-Odile Fortier-Masek');
INSERT INTO public.authors (id, name) VALUES (1340, 'Christopher   Clark');
INSERT INTO public.authors (id, name) VALUES (1341, 'Jean Rabe');
INSERT INTO public.authors (id, name) VALUES (1342, 'Antony Beevor');
INSERT INTO public.authors (id, name) VALUES (1343, 'Ian McEwan');
INSERT INTO public.authors (id, name) VALUES (1344, 'Alma Flor Ada');
INSERT INTO public.authors (id, name) VALUES (1345, 'Elivia Savadier');
INSERT INTO public.authors (id, name) VALUES (1346, 'Ken Follett');
INSERT INTO public.authors (id, name) VALUES (1347, 'Marcia Angell');
INSERT INTO public.authors (id, name) VALUES (1348, 'David Tennant');
INSERT INTO public.authors (id, name) VALUES (1349, 'Rick Riordan');
INSERT INTO public.authors (id, name) VALUES (1380, 'Craigss Robertson');
INSERT INTO public.authors (id, name) VALUES (1381, 'Craigs1 Robertson');
INSERT INTO public.authors (id, name) VALUES (1382, 'Craigs2 Robertson');
INSERT INTO public.authors (id, name) VALUES (1383, 'Craigs3 Robertson');
INSERT INTO public.authors (id, name) VALUES (1384, 'Craigs5 Robertson');
