create table genres
(
    id   serial
        primary key,
    name varchar(255)
        constraint uk_pe1a9woik1k97l87cieguyhh4
            unique
);

alter table genres
    owner to postgres;

INSERT INTO public.genres (id, name) VALUES (1, 'Juvenile Fiction');
INSERT INTO public.genres (id, name) VALUES (2, 'Boarding schools');
INSERT INTO public.genres (id, name) VALUES (3, 'Fiction');
INSERT INTO public.genres (id, name) VALUES (4, 'Astronomy');
INSERT INTO public.genres (id, name) VALUES (5, 'Biography & Autobiography');
INSERT INTO public.genres (id, name) VALUES (6, 'Language Arts & Disciplines');
INSERT INTO public.genres (id, name) VALUES (7, 'Europe');
INSERT INTO public.genres (id, name) VALUES (8, 'Travel');
INSERT INTO public.genres (id, name) VALUES (9, 'Fantasy fiction');
INSERT INTO public.genres (id, name) VALUES (10, 'Performing Arts');
INSERT INTO public.genres (id, name) VALUES (11, 'Computers');
INSERT INTO public.genres (id, name) VALUES (12, 'Unknown');
INSERT INTO public.genres (id, name) VALUES (13, 'Education');
INSERT INTO public.genres (id, name) VALUES (14, 'Young Adult Nonfiction');
INSERT INTO public.genres (id, name) VALUES (15, 'Literary Criticism');
INSERT INTO public.genres (id, name) VALUES (16, 'Large type books');
INSERT INTO public.genres (id, name) VALUES (17, 'Business & Economics');
INSERT INTO public.genres (id, name) VALUES (18, 'Games & Activities');
INSERT INTO public.genres (id, name) VALUES (19, 'Literary Collections');
INSERT INTO public.genres (id, name) VALUES (20, 'Transportation');
INSERT INTO public.genres (id, name) VALUES (21, 'Nature');
INSERT INTO public.genres (id, name) VALUES (22, 'Science');
INSERT INTO public.genres (id, name) VALUES (23, 'Drama');
INSERT INTO public.genres (id, name) VALUES (24, 'Crafts & Hobbies');
INSERT INTO public.genres (id, name) VALUES (25, 'Religion');
INSERT INTO public.genres (id, name) VALUES (26, 'Educational tests and measurements');
INSERT INTO public.genres (id, name) VALUES (27, 'Family & Relationships');
INSERT INTO public.genres (id, name) VALUES (28, 'Beads');
INSERT INTO public.genres (id, name) VALUES (29, 'Animated films');
INSERT INTO public.genres (id, name) VALUES (30, 'Monodramas');
INSERT INTO public.genres (id, name) VALUES (31, 'Cooking');
INSERT INTO public.genres (id, name) VALUES (32, 'Humor');
INSERT INTO public.genres (id, name) VALUES (33, 'Crime');
INSERT INTO public.genres (id, name) VALUES (34, 'Black people');
INSERT INTO public.genres (id, name) VALUES (35, 'Social Science');
INSERT INTO public.genres (id, name) VALUES (36, 'Juvenile Nonfiction');
INSERT INTO public.genres (id, name) VALUES (37, 'Science fiction');
INSERT INTO public.genres (id, name) VALUES (38, 'Young Adult Fiction');
INSERT INTO public.genres (id, name) VALUES (39, 'American fiction');
INSERT INTO public.genres (id, name) VALUES (40, 'United States');
INSERT INTO public.genres (id, name) VALUES (41, 'Romance fiction');
INSERT INTO public.genres (id, name) VALUES (42, 'Philosophy');
INSERT INTO public.genres (id, name) VALUES (43, 'Cryonics');
INSERT INTO public.genres (id, name) VALUES (44, 'Autobiographical fiction');
INSERT INTO public.genres (id, name) VALUES (45, 'Comics & Graphic Novels');
INSERT INTO public.genres (id, name) VALUES (46, 'History');
INSERT INTO public.genres (id, name) VALUES (47, 'Hindu astrology');
INSERT INTO public.genres (id, name) VALUES (48, 'Dogs');
INSERT INTO public.genres (id, name) VALUES (49, 'Political Science');
INSERT INTO public.genres (id, name) VALUES (50, 'Missing persons');
INSERT INTO public.genres (id, name) VALUES (51, 'Law');
INSERT INTO public.genres (id, name) VALUES (52, 'Technology & Engineering');
INSERT INTO public.genres (id, name) VALUES (53, 'Jews');
INSERT INTO public.genres (id, name) VALUES (54, 'Art');
INSERT INTO public.genres (id, name) VALUES (55, 'Music');
INSERT INTO public.genres (id, name) VALUES (56, 'Psychology');
INSERT INTO public.genres (id, name) VALUES (57, 'Conduct of life');
INSERT INTO public.genres (id, name) VALUES (58, 'Design');
INSERT INTO public.genres (id, name) VALUES (59, 'Christian life');
INSERT INTO public.genres (id, name) VALUES (60, 'Sports & Recreation');
INSERT INTO public.genres (id, name) VALUES (61, 'Poetry');
INSERT INTO public.genres (id, name) VALUES (62, 'Health & Fitness');
INSERT INTO public.genres (id, name) VALUES (63, 'Assimilation (Sociology)');
INSERT INTO public.genres (id, name) VALUES (64, 'Latin America');
INSERT INTO public.genres (id, name) VALUES (65, 'London (England)');
INSERT INTO public.genres (id, name) VALUES (66, 'Human engineering');
INSERT INTO public.genres (id, name) VALUES (67, 'Architecture');
INSERT INTO public.genres (id, name) VALUES (68, 'Memoirs of a geisha (Motion picture)');
INSERT INTO public.genres (id, name) VALUES (69, 'Anti-Catholicism');
INSERT INTO public.genres (id, name) VALUES (70, 'Everglades (Fla.)');
INSERT INTO public.genres (id, name) VALUES (71, 'Self-Help');
INSERT INTO public.genres (id, name) VALUES (72, 'Lesbians');
INSERT INTO public.genres (id, name) VALUES (73, 'Capitalists and financiers');
INSERT INTO public.genres (id, name) VALUES (74, 'Bodybuilding');
INSERT INTO public.genres (id, name) VALUES (75, 'Libraries');
INSERT INTO public.genres (id, name) VALUES (76, 'Cooking (Rice)');
INSERT INTO public.genres (id, name) VALUES (77, 'Assassins');
INSERT INTO public.genres (id, name) VALUES (78, 'Political leadership');
INSERT INTO public.genres (id, name) VALUES (79, 'Decision making');
INSERT INTO public.genres (id, name) VALUES (80, 'Dating (Social customs)');
INSERT INTO public.genres (id, name) VALUES (81, 'Afghan Wars');
INSERT INTO public.genres (id, name) VALUES (82, 'Love');
INSERT INTO public.genres (id, name) VALUES (83, 'Enthusiasm');
INSERT INTO public.genres (id, name) VALUES (84, 'Economic geography');
INSERT INTO public.genres (id, name) VALUES (85, 'Achilles (Greek mythology)');
INSERT INTO public.genres (id, name) VALUES (86, 'Aeneas (Legendary character)');
INSERT INTO public.genres (id, name) VALUES (87, 'American poetry');
INSERT INTO public.genres (id, name) VALUES (88, 'Christian pilgrims and pilgrimages');
INSERT INTO public.genres (id, name) VALUES (89, 'Compulsive behavior');
INSERT INTO public.genres (id, name) VALUES (90, 'Quality of life');
INSERT INTO public.genres (id, name) VALUES (91, 'Greece');
INSERT INTO public.genres (id, name) VALUES (92, 'Foreign Language Study');
INSERT INTO public.genres (id, name) VALUES (93, 'English drama');
INSERT INTO public.genres (id, name) VALUES (94, 'Cyclopes (Greek mythology)');
INSERT INTO public.genres (id, name) VALUES (95, 'Bacchantes');
INSERT INTO public.genres (id, name) VALUES (96, 'Greek drama (Tragedy)');
INSERT INTO public.genres (id, name) VALUES (97, 'Agamemnon (Greek mythology)');
INSERT INTO public.genres (id, name) VALUES (98, 'Greek drama (Comedy)');
INSERT INTO public.genres (id, name) VALUES (99, 'Cliffs Notes');
INSERT INTO public.genres (id, name) VALUES (100, 'Athens (Greece)');
INSERT INTO public.genres (id, name) VALUES (101, 'Autism');
INSERT INTO public.genres (id, name) VALUES (102, 'FICTION');
INSERT INTO public.genres (id, name) VALUES (103, 'Theology');
INSERT INTO public.genres (id, name) VALUES (104, 'Christian saints');
INSERT INTO public.genres (id, name) VALUES (105, 'Bible');
INSERT INTO public.genres (id, name) VALUES (106, 'Cooks');
INSERT INTO public.genres (id, name) VALUES (107, 'Current Events');
INSERT INTO public.genres (id, name) VALUES (108, 'Courtship');
INSERT INTO public.genres (id, name) VALUES (109, 'True Crime');
INSERT INTO public.genres (id, name) VALUES (110, 'Avalanches');
INSERT INTO public.genres (id, name) VALUES (111, 'Children''s literature');
INSERT INTO public.genres (id, name) VALUES (112, 'Executions and executioners');
INSERT INTO public.genres (id, name) VALUES (113, 'Adventure stories');
INSERT INTO public.genres (id, name) VALUES (114, 'Medical');
INSERT INTO public.genres (id, name) VALUES (115, 'Cosmology');
INSERT INTO public.genres (id, name) VALUES (116, 'Mathematics');
INSERT INTO public.genres (id, name) VALUES (117, 'Falconry');
INSERT INTO public.genres (id, name) VALUES (118, 'Biographers');
INSERT INTO public.genres (id, name) VALUES (119, 'Fairy tales');
INSERT INTO public.genres (id, name) VALUES (120, 'Character');
INSERT INTO public.genres (id, name) VALUES (121, 'Dragons');
INSERT INTO public.genres (id, name) VALUES (122, 'Old Norse language');
INSERT INTO public.genres (id, name) VALUES (123, 'Children''s stories');
INSERT INTO public.genres (id, name) VALUES (124, 'Whales');
INSERT INTO public.genres (id, name) VALUES (125, 'Art and literature');
INSERT INTO public.genres (id, name) VALUES (126, 'Greek poetry');
INSERT INTO public.genres (id, name) VALUES (127, 'Aeronautics');
INSERT INTO public.genres (id, name) VALUES (128, 'Readers (Primary)');
INSERT INTO public.genres (id, name) VALUES (129, 'Caves');
INSERT INTO public.genres (id, name) VALUES (130, 'Competition');
INSERT INTO public.genres (id, name) VALUES (131, 'Boys');
INSERT INTO public.genres (id, name) VALUES (132, 'Christian biography');
INSERT INTO public.genres (id, name) VALUES (133, 'Christmas stories');
INSERT INTO public.genres (id, name) VALUES (134, 'India');
INSERT INTO public.genres (id, name) VALUES (135, 'Conjoined twins');
INSERT INTO public.genres (id, name) VALUES (136, 'Children');
INSERT INTO public.genres (id, name) VALUES (137, 'France');
INSERT INTO public.genres (id, name) VALUES (138, 'Pets');
INSERT INTO public.genres (id, name) VALUES (139, 'Celebrities');
INSERT INTO public.genres (id, name) VALUES (140, 'Compulsive eating');
INSERT INTO public.genres (id, name) VALUES (141, 'British');
INSERT INTO public.genres (id, name) VALUES (142, 'Ballet');
INSERT INTO public.genres (id, name) VALUES (143, 'German fiction');
INSERT INTO public.genres (id, name) VALUES (144, 'Spanish language');
INSERT INTO public.genres (id, name) VALUES (145, 'Claustrophobia');
INSERT INTO public.genres (id, name) VALUES (146, 'Historical fiction');
INSERT INTO public.genres (id, name) VALUES (147, 'Australia');
INSERT INTO public.genres (id, name) VALUES (148, 'Arab-Israeli conflict');
INSERT INTO public.genres (id, name) VALUES (149, 'Family festivals');
INSERT INTO public.genres (id, name) VALUES (150, 'Jealousy');
INSERT INTO public.genres (id, name) VALUES (151, 'Man-woman relationships');
INSERT INTO public.genres (id, name) VALUES (152, 'Canadian nonfiction');
INSERT INTO public.genres (id, name) VALUES (153, 'Canadian fiction');
INSERT INTO public.genres (id, name) VALUES (154, 'Audiotapes');
INSERT INTO public.genres (id, name) VALUES (155, 'Aesthetics');
INSERT INTO public.genres (id, name) VALUES (156, 'Harriet the Spy (Fictitious character)');
INSERT INTO public.genres (id, name) VALUES (157, 'Dresses');
INSERT INTO public.genres (id, name) VALUES (158, 'Interplanetary voyages');
INSERT INTO public.genres (id, name) VALUES (159, 'Cookbooks');
INSERT INTO public.genres (id, name) VALUES (160, 'Paris (France)');
INSERT INTO public.genres (id, name) VALUES (161, 'Americans');
INSERT INTO public.genres (id, name) VALUES (162, 'Hyperion (Imaginary place)');
INSERT INTO public.genres (id, name) VALUES (163, 'Short stories');
INSERT INTO public.genres (id, name) VALUES (164, 'Soul mates');
INSERT INTO public.genres (id, name) VALUES (165, 'Books and reading');
INSERT INTO public.genres (id, name) VALUES (166, 'Existentialism');
INSERT INTO public.genres (id, name) VALUES (167, 'Ciphers in literature');
INSERT INTO public.genres (id, name) VALUES (168, 'Illuminati');
INSERT INTO public.genres (id, name) VALUES (169, 'Christian saints in literature');
INSERT INTO public.genres (id, name) VALUES (170, 'Jewish children');
INSERT INTO public.genres (id, name) VALUES (171, 'Islamic pirates-fiction');
INSERT INTO public.genres (id, name) VALUES (172, 'American wit and humor');
INSERT INTO public.genres (id, name) VALUES (173, 'Animals');
INSERT INTO public.genres (id, name) VALUES (174, 'Men');
INSERT INTO public.genres (id, name) VALUES (175, 'Forest products');
INSERT INTO public.genres (id, name) VALUES (176, 'Abnormal Behaviour');
INSERT INTO public.genres (id, name) VALUES (177, 'People with social disabilities');
INSERT INTO public.genres (id, name) VALUES (178, 'Object-oriented programming (Computer science)');
INSERT INTO public.genres (id, name) VALUES (179, 'Fathers');
INSERT INTO public.genres (id, name) VALUES (180, 'Karate');
INSERT INTO public.genres (id, name) VALUES (181, 'American literature');
INSERT INTO public.genres (id, name) VALUES (182, 'Healers');
INSERT INTO public.genres (id, name) VALUES (183, 'Conflict of generations');
INSERT INTO public.genres (id, name) VALUES (184, 'Motion picture plays');
INSERT INTO public.genres (id, name) VALUES (185, 'Military art and science');
INSERT INTO public.genres (id, name) VALUES (186, 'Latitude');
INSERT INTO public.genres (id, name) VALUES (187, 'African Americans');
INSERT INTO public.genres (id, name) VALUES (188, 'Adultery');
INSERT INTO public.genres (id, name) VALUES (189, 'Children of the rich');
INSERT INTO public.genres (id, name) VALUES (190, 'Biography');
INSERT INTO public.genres (id, name) VALUES (191, 'Detective and mystery stories');
INSERT INTO public.genres (id, name) VALUES (192, 'Photography');
INSERT INTO public.genres (id, name) VALUES (193, 'Babytime resource');
INSERT INTO public.genres (id, name) VALUES (194, 'Berlin (Germany)');
